---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prowlarr
  namespace: argo-system
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://bjw-s-labs.github.io/helm-charts
    chart: app-template
    targetRevision: 5.0.1
    helm:
      releaseName: prowlarr
      valuesObject:
        defaultPodOptions:
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
            fsGroup: 1000
            fsGroupChangePolicy: OnRootMismatch
          resources:
            requests:
              memory: 256Mi
              cpu: 100m
            limits:
              memory: 512Mi
              cpu: 200m

        service:
          main:
            type: ClusterIP
            controller: main
            ports:
              http:
                port: 9696

        route:
          internal-gw:
            enabled: true
            kind: HTTPRoute
            hostnames: [prowlarr.home.cianfr.one]
            parentRefs:
              - name: internal-gw
                namespace: networking
                sectionName: https
            rules:
              - matches:
                  - path: { type: PathPrefix, value: / }
                backendRefs:
                  - identifier: main
                    port: http

        controllers:
          main:
            type: deployment
            replicas: 1
            strategy: Recreate
            annotations:
              reloader.stakater.com/auto: "true"
            containers:
              main:
                env:
                  PGID: 1000
                  PGUID: 1000
                  TZ: Europe/Amsterdam
                image:
                  repository: ghcr.io/linuxserver/prowlarr
                  tag: 2.5.2@sha256:2f3d31307beba3ba2dd226d191f5f5c14ee3b4d8b49277c64683f5ed97083179
                probes:
                  liveness: { enabled: false }
                  readiness: { enabled: false }
                  startup: { enabled: false }

        persistence:
          config:
            enabled: true
            existingClaim: prowlarr-config-v2
            globalMounts: [{ path: /config }]
            type: persistentVolumeClaim
          media:
            enabled: true
            existingClaim: media-data-v4
            globalMounts: [{ path: /data }]
            type: persistentVolumeClaim
  destination:
    name: in-cluster
    namespace: media
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - ServerSideApply=true
      - ApplyOutOfSyncOnly=true
      - SkipDryRunOnMissingResource=true
