---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: immich
  namespace: argo-system
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://bjw-s-labs.github.io/helm-charts
    chart: app-template
    targetRevision: 5.0.1
    helm:
      releaseName: immich-server
      valuesObject:
        defaultPodOptions:
          securityContext:
            fsGroup: 1000
            fsGroupChangePolicy: OnRootMismatch
            runAsGroup: 1000
            runAsUser: 1000
          affinity:
            nodeAffinity:
              preferredDuringSchedulingIgnoredDuringExecution:
                - weight: 100
                  preference:
                    matchExpressions:
                      - key: cianfr.one/gpu.transcoding.speed
                        operator: In
                        values:
                          - fast
                - weight: 50
                  preference:
                    matchExpressions:
                      - key: cianfr.one/gpu.transcoding.speed
                        operator: In
                        values:
                          - medium

        service:
          main:
            type: ClusterIP
            controller: main
            ports:
              http:
                port: &http-port 2283
                primary: true
              metrics-api:
                port: 8081
                primary: false
              metrics-ms:
                port: 8082
                primary: false

        route:
          main:
            enabled: true
            annotations:
              external-dns.alpha.kubernetes.io/hostname: photos.cianfr.one
            hostnames:
              - photos.cianfr.one
            parentRefs:
              - name: external-gw
                namespace: networking
                sectionName: https
            rules:
              - matches:
                  - path:
                      type: PathPrefix
                      value: /
                backendRefs:
                  - identifier: main
                timeouts:
                  request: 600s
                  backendRequest: 600s

        controllers:
          main:
            type: deployment
            replicas: 1
            strategy: Recreate
            annotations:
              reloader.stakater.com/auto: "true"
            containers:
              main:
                image:
                  repository: ghcr.io/immich-app/immich-server
                  tag: v3.0.3
                env:
                  TZ: Europe/Amsterdam
                  IMMICH_TELEMETRY_INCLUDE: all
                  IMMICH_CONFIG_FILE: &config-file /config/immich-config.yaml
                  IMMICH_MACHINE_LEARNING_URL: http://immich-machine-learning:3003
                  REDIS_HOSTNAME: immich-redis.media.svc.cluster.local
                  DB_HOSTNAME: immich-cnpg-cluster-rw.media.svc.cluster.local
                  DB_DATABASE_NAME: { valueFrom: { secretKeyRef: { name: immich-cnpg-cluster-app, key: dbname } } }
                  DB_USERNAME: { valueFrom: { secretKeyRef: { name: immich-cnpg-cluster-app, key: username } } }
                  DB_PASSWORD: { valueFrom: { secretKeyRef: { name: immich-cnpg-cluster-app, key: password } } }
                resources:
                  requests:
                    gpu.intel.com/i915: "1"
                  limits:
                    gpu.intel.com/i915: "1"
                probes:
                  liveness: &liveness-probe
                    enabled: true
                    custom: true
                    spec:
                      httpGet:
                        path: /api/server/ping
                        port: *http-port
                      initialDelaySeconds: 0
                      periodSeconds: 10
                      timeoutSeconds: 1
                      failureThreshold: 3
                  readiness: *liveness-probe
                  startup:
                    enabled: true
                    custom: true
                    spec:
                      httpGet:
                        path: /api/server/ping
                        port: *http-port
                      initialDelaySeconds: 0
                      periodSeconds: 10
                      timeoutSeconds: 1
                      failureThreshold: 30

        serviceMonitor:
          main:
            enabled: false
            endpoints:
              - port: metrics-api
                scheme: http
              - port: metrics-ms
                scheme: http

        persistence:
          config:
            type: secret
            name: immich-config
            globalMounts:
              - path: *config-file
                subPath: immich-config.yaml
                readOnly: true
          external-videos:
            type: persistentVolumeClaim
            existingClaim: media-videos-v1
            globalMounts:
              - path: /external/videos
          external-library:
            type: nfs
            server: truenas.home.arpa
            path: /mnt/pool0/gallery/external
            globalMounts:
              - path: /external/library
          library:
            type: persistentVolumeClaim
            existingClaim: immich-library-v4
            globalMounts:
              - path: /usr/src/app/upload
              - path: /imported
                subPath: imported
  destination:
    name: in-cluster
    namespace: media
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - ServerSideApply=true
      - ApplyOutOfSyncOnly=true
      - SkipDryRunOnMissingResource=true
