apiVersion: v1
kind: Secret
metadata:
    name: immich-config
    namespace: media
type: Opaque
stringData:
    immich-config.yaml: ENC[AES256_GCM,data:w5d2phQHi8j1e7sJ7wNXtIRI/oiJDPq9YSCM4/nG5lmAiIMiVRUJpr1jZLxMmXVIT35/iMKTtpRiHM4QBL4JhjhHbSg1Y3ShCqDQukS84P8lD4Pd38Jl78xdpzt37kq5Mz0YXQxozG6hU+QlLsvYpqvIVetZxgFMv92AIVsG4hXedSVW3Y0qNROsSSrwfMnfAfk47o9Hw5tO05I6EAnBRforhfECd7w6NfmTWoZuwT8HIgLXcHEz5PX9URX9VCE5X1xc6KLgLhZJy0wnlQAAyZ1d/BPoV0zAhELn8rO8YcBDwD5bOpAonnc2QF9O6+AjeoVaVckLGYO0mFAUMOtPNetqpU2DP4ZMWKbPmxSDizIuUMrDFt3pcHFqwfShb9RRh3Zj2EdPQ1hkQVMuBZLMU7NBcbK90JLfo9jFw3fAzGMwh+xJUMxqkln8j26SZrSe8B8wpj31ese4FJhTuJwAfQoPtwvRv1z4J10rqA3G48rZ8sxIxI2IFQ22IAwZabaRh7MbYWyMm5OkHduwe2/xJRlm+tCx3WoX4vc75cGZidtNlLIyIBaEKXPRvSVEme//JElnsIuKJdlJonN2nFb2o8Uo4MKhg642Ho2ds1jvSyA1J+UkvaYYhVco0FiZmaRcgN2z7Wx6m/p0xB9IVBLZNU3yyHcdpYcy1mJISMSzUROrvw4iQEJw/z+VRkIlLXt9M5EpJqjit25HOVk99SLISBeisLqzL3M1RkjXGYH+S+Dr0kRhAoSGOlfBQsNgzmIoAxkPZd8miZwSnlICQgXWqD9GVf0rvnWoVlLYOvCou/k5FlcL9NHOZHwjQ+XtwJqfk96R30PIajFJUVbl4ZUqxuaI,iv:G5upHs6GXru67s16mwvt/SiYmpSdd4Ncm8YexR3arFs=,tag:QaVmEWiiuGXTRnNjKy8dsA==,type:str]
sops:
    age:
        - recipient: age1m38eu4srfs6puqtrpcazlu5kv24fd57yda4p505k9msqjwzttujs825kzl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArRlE4YjZpai9OM3lhYnlR
            Q0wrbVY3Q0VHY0xyaGU0cG9leDEyODFkL0JFCjlXVDIyK09WR1VMOHhNTUEzNVM1
            YkNpWlk4aWZaWHp2c1E0NldLMy8zZWMKLS0tIG9TTjVLV0F5MTEwR0FPTVFRZkJK
            L2VsNVpib0pwVGFtZzBteFNIaUNYL1kKzxA5bHCKWyqhlYgv9r0I6K17yTepf6pe
            LHki+F298bkz5clXwhPFMGbYZvoVbHeO0FwI2Bo1PxTFURoy9GRfDA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-14T15:52:01Z"
    mac: ENC[AES256_GCM,data:BqURLqqSmgVYbFJcuGFpMlxyucA6Yq5RnB5g5M1JVhwak6+toEjqD4dlO5F/0bCJD1vswvXNr8RH6YAkWzT1tcqjU1BQbqy550jLF8soG+akHaI7AHKB3VtQ/aOkjZ6oCw41Ov55vJUAHRdfGvocdOwRacemnKd2TY6NkdN1Tgs=,iv:R74EvSXdhLv/PZoGYj84imFdTB/kf4TJjiN1crcYSQQ=,tag:+ZrtVARPs+wC6KDryroeZA==,type:str]
    pgp:
        - created_at: "2025-11-23T21:45:10Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIOA4TLBMScuBokEAf/VeNBGh45nfV4EXX7XQE/N2oIUeMRtM4YZiop0rTjTxJf
            OoIJ4oWk7Gm7bWz21f7RhMh7wqpUirHGRppaJHbRVju8vgvZsV/yGJeeOQhIhPZ9
            /uykCB26rOzqDNmkAkYNxczMet0fho4WPJRMYfiy1+d1MOh7HxrpptxOnj5iHhYh
            OHa0qkBy0Bhhd0aHdByzL6pT7Oyt9iXl3+1cH9DCMarx2gHAxAOwU6OHlrOyNGSQ
            xLeixI/1ImxOPmHoL0+Ag/sygI6ZYBBI3Rb3e/vx8YGFKx5rZ+ZFhVCw7+C1/vRe
            brXBk2q6aYErnFNfTCjnJLF2IPytBUF/H9+fp12O6gf/e5t12zr1umgMC9MuNIRD
            uIZXK76xuB9suBSjJvKlUJ1C/r30WdsVJ/YKmRzJt9CJR8FRo+PRLx4OkwbeBfka
            AWbd6FhonBDGyi2L2iOavQ3eQZS6tUCO2J/1n49ZYU9ltMQu6DXj8fZuWbL2vLPL
            bsvyTNXrCn5kMrvI0YsqybKwuM7DSJrBiIfjiJOHSnBkQe0eWWk/TVQM/9P0iHBo
            fT8WaGdJVbvaXyeRUeZ0JGeejbSe3pRth9AWETIvK7/zZEd5dDfUcmKMj+tBDtas
            CaMwXknDKqFjnnZ28LRoTeMYWQWq+y7i7weOoFBkGiIdcByQtYqkLPy6oWZgqSCq
            3dJeAQsppTWlIr3q3/Wl7plfYuQkGDBIWS9G9NOJ6SNNitBhiLjW6x/sD4pn2rTJ
            WsH3NFNhMaafDaAlDg6eokoXcU9M6D5HfxCX+4bSXY2ghMYlmlXbsY6yBjJaoBBJ
            BQ==
            =AG3w
            -----END PGP MESSAGE-----
          fp: C8DAE39DAA00FF97
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
