# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/values.schema.json
---
defaultPodOptions:
  securityContext:
    fsGroup: 1000
    fsGroupChangePolicy: OnRootMismatch
    runAsGroup: 1000
    runAsUser: 1000

service:
  main:
    type: ClusterIP
    controller: main
    ports:
      http:
        port: 8686

ingress:
  tailscale:
    className: tailscale
    enabled: true
    hosts:
      - host: nl-lidarr
        paths:
          - path: "/"
            pathType: Prefix
            service:
              identifier: main
              port: http
    tls:
      - hosts: [nl-lidarr]

controllers:
  main:
    type: deployment
    replicas: 1
    annotations:
      "reloader.stakater.com/auto": "true"
    containers:
      main:
        env:
          PGID: 1000
          PGUID: 1000
          TZ: Europe/Amsterdam
        image:
          repository: ghcr.io/linuxserver/lidarr
          tag: 3.1.0@sha256:ca2f95634d422fdeccfbff2a42cbe3a4fed1170f7e3546d99d5d5f2c9c9aa03b
        probes:
          liveness: { enabled: false }
          readiness: { enabled: false }
          startup: { enabled: true }

persistence:
  config:
    enabled: true
    existingClaim: lidarr-config-v2
    globalMounts: [{ path: /config }]
    type: persistentVolumeClaim
  media:
    enabled: true
    existingClaim: media-data-v4
    globalMounts: [{ path: /data }]
    type: persistentVolumeClaim
