---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sabnzbd
  namespace: argo-system
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://bjw-s-labs.github.io/helm-charts
    chart: app-template
    targetRevision: 5.0.1
    helm:
      releaseName: sabnzbd
      valuesObject:
        defaultPodOptions:
          securityContext:
            fsGroup: 1000
            fsGroupChangePolicy: OnRootMismatch
            runAsGroup: 1000
            runAsUser: 1000
          affinity:
            nodeAffinity:
              preferredDuringSchedulingIgnoredDuringExecution:
                - weight: 100
                  preference:
                    matchExpressions:
                      - key: cianfr.one/networking.linkspeed
                        operator: In
                        values:
                          - 2500Mbits

        service:
          main:
            type: ClusterIP
            controller: main
            ports:
              http:
                port: 8080

        route:
          internal-gw:
            enabled: true
            kind: HTTPRoute
            hostnames: [sabnzbd.home.cianfr.one]
            parentRefs:
              - name: internal-gw
                namespace: networking
                sectionName: https
            rules:
              - matches:
                  - path: { type: PathPrefix, value: / }
                backendRefs:
                  - identifier: main
                    port: http

        controllers:
          main:
            type: deployment
            replicas: 1
            strategy: Recreate
            annotations:
              reloader.stakater.com/auto: "true"
            containers:
              main:
                env:
                  PGID: 1000
                  PGUID: 1000
                  TZ: Europe/Amsterdam
                image:
                  repository: ghcr.io/linuxserver/sabnzbd
                  tag: 5.0.4@sha256:b67039e6739c2379f2eac8901248cdfcd78536ee34fe6948faea6b8ce8b4805b
                probes:
                  liveness: { enabled: false }
                  readiness: { enabled: false }
                  startup: { enabled: true }

        persistence:
          config:
            enabled: true
            existingClaim: sabnzbd-config-v2
            globalMounts: [{ path: /config }]
            type: persistentVolumeClaim
          downloads:
            enabled: true
            existingClaim: sabnzbd-downloads-v2
            globalMounts: [{ path: /downloads }]
            type: persistentVolumeClaim
          media:
            enabled: true
            existingClaim: media-data-v4
            globalMounts: [{ path: /data }]
            type: persistentVolumeClaim
  destination:
    name: in-cluster
    namespace: media
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - ServerSideApply=true
      - ApplyOutOfSyncOnly=true
      - SkipDryRunOnMissingResource=true
