---
# yaml-language-server: $schema=https://www.schemastore.org/kustomization.json
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - application.yaml
  - sabnzbd-config-v2.yaml
  - sabnzbd-downloads-v2.yaml
