---
# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/refs/heads/master/v1.34.2/persistentvolumeclaim-v1.json
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sabnzbd-downloads-v2
  namespace: media
  labels:
    recurring-job.longhorn.io/source: enabled
spec:
  storageClassName: longhorn-nvme-1-replicas
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 150Gi
