---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: descheduler
  namespace: argo-system
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://kubernetes-sigs.github.io/descheduler/
    chart: descheduler
    targetRevision: 0.35.1
    helm:
      releaseName: descheduler
      valuesObject:
        kind: CronJob
        schedule: "*/15 * * * *"
        activeDeadlineSeconds: 600
        successfulJobsHistoryLimit: 3
        failedJobsHistoryLimit: 3

        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 256Mi

        deschedulerPolicyAPIVersion: descheduler/v1alpha2

        deschedulerPolicy:
          profiles:
            - name: default
              pluginConfig:
                - name: DefaultEvictor
                  args:
                    podProtections:
                      defaultDisabled:
                        - PodsWithLocalStorage
                - name: RemoveDuplicates
                - name: RemovePodsHavingTooManyRestarts
                  args:
                    podRestartThreshold: 100
                    includingInitContainers: true
                - name: RemovePodsViolatingNodeAffinity
                  args:
                    nodeAffinityType:
                      - requiredDuringSchedulingIgnoredDuringExecution
                - name: RemovePodsViolatingNodeTaints
                - name: RemovePodsViolatingInterPodAntiAffinity
                - name: RemovePodsViolatingTopologySpreadConstraint
                - name: LowNodeUtilization
                  args:
                    thresholds:
                      cpu: 30
                      memory: 30
                      pods: 30
                    targetThresholds:
                      cpu: 70
                      memory: 70
                      pods: 60
              plugins:
                balance:
                  enabled:
                    - RemoveDuplicates
                    - RemovePodsViolatingTopologySpreadConstraint
                    - LowNodeUtilization
                deschedule:
                  enabled:
                    - RemovePodsHavingTooManyRestarts
                    - RemovePodsViolatingNodeTaints
                    - RemovePodsViolatingNodeAffinity
                    - RemovePodsViolatingInterPodAntiAffinity
  destination:
    name: in-cluster
    namespace: kube-system
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - ServerSideApply=true
      - ApplyOutOfSyncOnly=true
      - SkipDryRunOnMissingResource=true
