---
apiVersion: v1
clusters:
  - name: home
    cluster:
      server: https://home-k8s.tail2ff90.ts.net
contexts:
  - name: home
    context:
      cluster: home
      user: tailscale-auth
kind: Config
preferences: {}
current-context: home
users:
  - name: tailscale-auth
    user:
      token: unused
