---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: snapshot-controller-selfsigned
  namespace: longhorn-system
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  selfSigned: {}
