---
# yaml-language-server: $schema=https://www.schemastore.org/kustomization.json
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - application.yaml

configMapGenerator:
  - name: searxng-config
    namespace: default
    files:
      - settings.yml

generators:
  - ksops.yaml

generatorOptions:
  disableNameSuffixHash: true
