apiVersion: v1
kind: Secret
metadata:
    name: searxng-secret
    namespace: default
type: Opaque
stringData:
    secret-key: ENC[AES256_GCM,data:PA6eO7nKEkzDjp2B1yUZEFMaDCUcSX9COjI5YiB4lwQE0z81d8rUbH/nV/3GFG+o4YES5FoXtA8lR4eCFgm1lQ==,iv:Af3SlgFhec6j6vjFOljr610hgMD+QSC6ELBvA8B4FIA=,tag:yrmWZLfyIaIM1WIHET8lVA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiY1VKWWUxV3BiTG55L3c0
            a1laWG5ieFBicXlRZGMwSVpaRFB4aWU0NW5vCkxxcWNYWkhEc0Z0encramFFZVBV
            bDQxT3pWTmoxbDdlbi9pbGx2cDN0R2sKLS0tIGtvM0hRdVB2S3l1RE5vOHV6cWIx
            a1Y1S29iaTlZQmgvRjVqeUVUYjJOb0EKzfQgXlWm502oCwiyTgdbnnCVdRjQV+su
            9hSXRhAMj7AkcpQGgzzX9kLh8Oq8hOcNHeD10nMkb7ar8r1y+hvLzA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1m38eu4srfs6puqtrpcazlu5kv24fd57yda4p505k9msqjwzttujs825kzl
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-31T14:59:09Z"
    mac: ENC[AES256_GCM,data:tArs23M/IjgEBrrbFnjKazWwGiWrO8u4dQX14LrHQdc22rQIEikQXfThAVPnXxonWwKdwyQ+dpvAp9/bmJh/YOS1BEibgkjLeXB0rDCt+kDjw721G7gIJlXrs7OZs/+uiboCzbKM8Zj0Nr5w/0/pMJL5hj8Vi1pIXmuZLwwL2eo=,iv:CsEF7hjJZvQTen32xenyv60cXPr4YCJPiB8xEWbbUfs=,tag:5ulgrDiUC70Z3BqM3xTWLg==,type:str]
    pgp:
        - created_at: "2026-08-31T14:59:09Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIOA4TLBMScuBokEAgAg3EdEkGpFupa5zDun15Y5ungxNBC9E9d4GorwnlUJqj1
            xfkaKe9CSEQRe8W/tgkQ7VdTT5AoiLBydaRRtqpsBvV5swbw40usXnJXPpssnjEc
            80Mbfxj0vgkdBlqof1w5suij6mXnomrgWv0milv9WO+4taOKsNTZWg/P9gK3rRmX
            QbdNlgqEIpkzWIqXHa8QA059QLugKT+OXS/DchWBeGAkVuQKEZVxmPpLn7q0y7kP
            qYpfNYfNG6T5tYyWtPNTOzZgC+kHEqv2sP6NJ1RmP3R9v4qSJga+bJEwhTXH4wMx
            0qAJTgT9exFmShxPhLuj6E4xQWBPog+J3sE2/OygpwgAgTWssMm51opd2mjWnFxj
            Yd4lt3MhU6J5GFO5uVlYy+CKAUvRhBtk+jMqYhopcfJPh/qbUEdhnDH+ssxhkN+1
            gdcv4jvEzvzP7GatrmLiYN5P71J6/GjMEKCmHoNWt1h9cd8fxBE/Zb7mTJH1JsXA
            Td3G3A89J9BoozU09o39v3ZnbDMH7eFv1b/kd2UE1/rp6y8H6DFqMx/el9ld4ZPx
            nvKs4Z9MkX/uFvNDAvb5JW12ey7IMLHJdr4j1zxZHWQ7QLgR8zNdR6VM82jADWTd
            8sKBXBE9yWVmCFtJDmlVG42RU91NAlGrqGTP0uZrkMz+glpHhDpZvl7/m8f2de7E
            K9JeATOEx9aChfe1mrK0tgevGziyo5ZOYSwtnfCTeYEXqmmBCkmXY5qga4kvpISf
            RhEGN+qbuThgov9DEZVcW+NjFhj4Osealzm2j7Hud51XZl6Rv2oiB2Nuvk1yqnq4
            TQ==
            =OWxb
            -----END PGP MESSAGE-----
          fp: C8DAE39DAA00FF97
    version: 3.13.2
