---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: media

resources:
  - statefulset.yaml

helmCharts:
  - name: redis
    repo: https://ot-container-kit.github.io/helm-charts
    version: 0.16.9
    releaseName: immich-redis
    namespace: media
    valuesFile: values.yaml

patches:
  - target:
      group: redis.redis.opstreelabs.in
      version: v1beta2
      kind: Redis
      name: immich-redis
    patch: |-
      - op: add
        path: /metadata/annotations
        value:
          redis.opstreelabs.in/skip-reconcile: "true"
