# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/values.schema.json
---
defaultPodOptions:
  securityContext:
    runAsUser: 1000
    runAsGroup: 1000
    fsGroup: 1000
    fsGroupChangePolicy: "OnRootMismatch"

service:
  main:
    type: ClusterIP
    controller: main
    ports:
      http:
        port: 8191

controllers:
  main:
    type: deployment
    replicas: 1
    annotations:
      "reloader.stakater.com/auto": "true"
    containers:
      main:
        env:
          LOG_LEVEL: info
        image:
          repository: ghcr.io/flaresolverr/flaresolverr
          tag: v3.5.0@sha256:139dfee1c6f89249c8d665d1333a42e8ec74ec0a86bc6bb1c8461e10d3a66a47
        probes:
          liveness: { enabled: false }
          readiness: { enabled: false }
          startup: { enabled: true }
