# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/refs/heads/master/v1.34.2/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
    name: argocd-homelab-repo
    namespace: argo-system
    labels:
        argocd.argoproj.io/secret-type: repository
type: Opaque
stringData:
    type: ENC[AES256_GCM,data:ihmZ,iv:GciQubsUO97lEjFWJZE9IkDSWfCE2r+g66xCcG4d7Dw=,tag:L1dxlPamKT5BBpPKGu3DuA==,type:str]
    url: ENC[AES256_GCM,data:gGSGOLrdWZiYLtyQohO3W4EHwu1RiyCMx+TnHHDfcker2tje,iv:naSVOSPgLin6mWHZoBKElsUcu7Id13Zc9bgamOcnyHc=,tag:nQeVUW8j3vKB31TGeNKXWQ==,type:str]
    sshPrivateKey: ENC[AES256_GCM,data:ddcXZACxdjoV+bjpmr4bdYMtziPOD9oJ9f56RgklO+TR1oKDY69mRzmTZ8PIE9qYw/S0bZnUNpVaRHixtXWnUCIKx9WEn6OJR1la6PiyxgNm71hhtwRW8Ztu4OGuqHwEUgNHZisl+4IWUux+JmpWHOboNH6w4FnM5AZJ9+vY4JS/hv3LmYvyNmZAjyPrx2kxL7OjFpu48TFEtIEJHnpZmKBn2g1pHBFDlKl71T5jUJxbaQYNpNQipBgTUUNsrTDO1f3zRI8q0ZV94VKIO7MCvdtnkipQXLbJboZB13LvRHfgs8udAVJb0wMqpgzTAaotvM17t2TBliwC5/+0bFvvjPY22XcGP9yhNO3Qb40XPYtc/DJ7LffC25Pbe6JYN4Uj5p9CukPTtCk4eKom29RSYRPLydjH3aMkFeeDWmgjVFhcbKfDrZlCmLDQhD36FA64/9gCpSIcFWjxg/TRwlNhlg9Pa9SbrtkMzRXWY8y/72FcyDVm3/d2LWhnjs/D6vNbtkoEpOBx7TWVFVAn+UhewivFnhrctPNnalR5,iv:6z+8uDZbioV1UXM98tpsHi8rlR6hQ4YLaASjZ4UQdXM=,tag:a7i7ZG0z1Tf06ydOkt46yw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQQ0ZlWDByVWtJVGtTMlB6
            UWJ4RW9WaG41NG5BSkVId1hXYzNPVzVHUHhjCjhJSHZraTR4TVc4VmhFK2xQbzMv
            d0s0eDhXMStnRTBUb1hzR3JGdzA5S0UKLS0tIFhKdmZ3ZUwrK1V0N3k4Qk5rUUZC
            T0lFU1FNMDZYTHcvaFpoQ2FMbFNPZmsKYnHUtaVNn9/dYqCYfr5kXtT+SAAaJhmy
            9qCXzN02yVRV/goVZNa8EIoCe6xLwLUP/Mllw88gfWdblhQyQZGBhg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age18eehnlpn44hpk4d823zfnkq72vqmf6kqhrh009uwdajneeaqzskqscx589
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmOGJHd2NXdGNadXhRbTVH
            ZzIzVHV6TUx4dklReXF6TUVOZ2R2TWpSVUNNClh4SW5mV2loeXFCYTRKaTZ4ZjJy
            c3EzM0RmZXhCejVqbnZPQkNSRWNYQzgKLS0tIFNPSE9kdUJhVHRIKytzZTdaWGNH
            aHQvQVBZelh0NDdidVIxeHZwNldnQUEKJorFVTV7xtiOutBrXRwBB5Y4Gu4QdVXf
            8XwYk52hDt6Csj6WBm+ZY93kdY9cbGCd0Pzjst+5rO6z+hk2yCtArw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1krvwskkgw5f3ufcwgl6l2jz0emxnkn40wpup2aqhqdulqy2x99js4p5fnq
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJSlQ5NUM0eHNLSWJtM2F2
            dEpvaU93OHJHOHVKOXBTWFptdTVsSHZNdFZ3CmhLOG1EdmtzUWxoY2RKQlZNZ0lQ
            eGhyRUxDMVBvSXNxYlVHU1VXclZwVDgKLS0tIFA2T3F6bHpEdUVqYlBnWHBkTGFW
            YmtNdTR3NzhuVHFDazhlWGtsKzVWdVUKZhT9kbky1cobbO4tmb2rMcx2atl7CwHo
            n8BvV/swM8m7LiMYqzjiTV+fyoL3smbplJEMb+K4G8jmyli0ECASVg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age143yn95y2n546rlqrhgy2nzrz0w87ks7fk9dlwp3ylt0dfflczuhqrv2lmv
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvOWRDUVl1SGRmUmp6aFB0
            aFBmTjk2eWovUE55dU5sbDRzMnNNQW45R0NnCkEzdE50MzNuRlZyVXR1dEZzTXdB
            dVFWa0NRMWd4YWRibnBFVDI1VEgzR2cKLS0tIGpUam16VnhsQ2VJZGtOcGk0b242
            d0ljYmhoRDdVcTNONFU0Y1pYTlRYSmcKippjnmPuBm5vtfFiJrXP9XGfeXr/SPbm
            fdOYsZt7GdmpGPw+H7adTkkCRcvCTYmuNS6/CKDFMhDYUVzOuA2l3g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1n6eedefn6afu4e2f492xhfhckrayvp65jp7hla3x4nwj2zwz7sasw6ls6k
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPVEFnMGFnbk5xbDNRUXRF
            b0pkZ1l1NklzSzBVUFpxNXZHbHA4ZTJ1UDJJCllvUkpzY0NuNTFPeFZ1eDlSNTF5
            ZElxY2UweE1XQWlTYnlXVnBORmptVjgKLS0tIGRJRHZvYXJNVkViRStpdzdiZHFF
            RlFZTzBBWDVUWVd4NVFURzVRYktSMEEK3Ag3OagrL++REXX3ix0cAZWV137dS+GF
            R9zI9KDNgsAIcpzOpJ6PrrEZVePZwfJoQz8/pdO4Fu1zmMBPC3sVxg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age12g62sqmpz4pztx8zn94n8rxzklj7fj805g78m50kxu44yqy26azs2vph2y
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoMFVyVFJRU2dnZWpBejZY
            djZJcVZpVWhxRnpqbzMwWWRWaGtkZnBzVERrCnZMckJqb3g0bWR6M1p1Y2FEY1BK
            R3oxZEdZZlVrMVA3dUxWak1tckFJUkUKLS0tIGRQaDhlUm1hcHExaGZtdHZKTDgz
            SlVJMEtCUFdpalRBV1BBdGl6ajZoWDQKTD5B5JzQtuQyKOXvYVcHWe4Xhjl1r1BL
            ZDq5zTfzhkrd8vBvd9LNDmH4FOF2RwMGGN3m8O8fCDqRkfq4e+wD2g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1tcaqw9c5sfdys359kzs2t599d2sje7sg7fha8ts42955qk9t3yss075kcn
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-03T13:50:03Z"
    mac: ENC[AES256_GCM,data:GTmKy8wHFTrnOA7xLK4VV0wWnzUhcQ3Ts7zuWsXmj+pFVoGKdrr6SjD6haIR1PPD4gS3BstM0bCCb3hWa5da2o290RxUWzFahFXKsFq+6SE8e9I1KeswqtUM/rZ8TYNXWth+9gG0pIikY5FKZtxQN2Ht9aqaHkpYUFGJbI33rio=,iv:M+ejmTxb6WANtqJ7rbMLgD183MPu9otUU0PIoMnmkRc=,tag:gLYmYnTbTFL2pSMg1ftSkg==,type:str]
    pgp:
        - created_at: "2026-05-26T16:08:03Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIOA4TLBMScuBokEAf9EkVrMvh7k07EJH6yne61LjdccYynh9d6Sg1Z+rMK+Tvj
            v6ROVNexLRZ6nxFnpExDalxt36npKWb/ri3dKr/OvSyAHe+Tb5SEMJWIiavTfFG8
            uzesW73fwNvbVDe6mK3cKQpTlSxDtYmCCEGa+4fQR+mb+Q7UHdKCbRpO+tOTA/1X
            o+eVcXDqUCIL5vlP9S7BMXeDJGWGPYlEpR72kIyh8WdzKuii79+cO+vmQS6zt99k
            Til+zw+wQt21SBVqHlc28Z3EB0Xsz7Tinu9Ybx2PYebhjHLKdf+P9iMXPWxtN26u
            TrGRrAy+zLunqvu1Ca9//1GZamm9xf0jULRRC7Lkqwf/dHD1sAtoXLbn4k0XCXAf
            MvAs3o4qTOoADONdQc0e3JG20XASXMgk0QlZlw1C/rMtYemsDqX/QxOhln8zQzE/
            u+cRj3L+u1168Jsxu07NKxjAMsPbkOiCj/f001I48GERbWrKzLqQvllcMS/dTkFn
            wV5ga4QRNWHi5swLRhGm1rvluzWPR5pjPRq/SIWEnpU0Eg7f+m+VdmsqB6lrcmcR
            v/BoCUFBUPq/GjKSbwj+F6fh1XaPV9k1r1m/7dHyYnmDDDOZ545F4HIEZ5ORElgd
            Q7FFOWzz5eyZ/SskPyK5oEh7joL6WeiZIEdcKwxbO/hjAGBaxl852dgFw8UC0o0Y
            6NJeAfxKSYlz4FYl359bYcBfnKy0xG29T7qtFq9QXf9OrCB9CfJoUUhY/sku8JmV
            hyYsvM1Qfrmee4j/OyjQVBtbzF4+AXv+Dc09GeO4BFgC0a2dbEvoKsFg9+HiMXwV
            RA==
            =Xci5
            -----END PGP MESSAGE-----
          fp: C8DAE39DAA00FF97
    version: 3.13.1
