# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/refs/heads/master/v1.34.2/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
    name: flux-ssh-auth
    namespace: flux-system
type: Opaque
stringData:
    identity: ENC[AES256_GCM,data:zQwzNKibXVf6D9p/FLEgSAgWsfi36sWO0xtuz2a4Nj6USt4hVFlVCfXydfYcsMp9Ykfcqv94jKHNO2K2X9YpIv2W9TyYdQh5JcnAwcWwtEy78NOp6REhLlBYDaRcKOoq9QoiUdzwLt8NM0UI+PiNDvvmLqvGsrpRTAI4TFPVjJNNcQBf7NuRr2AKTnbjksnt4prBbYS0yXK3NPcf/tZB5HHCXE9+tyhQETdIAvYsQ/R2aXa6X2QhuBMwKmn5+x3lRGHxXTJC6r+U4xt/N6+irYrp97+tcNZxGbCNWsBGk3seh8FDgdMJ6b5rMrfy0OE2caMdSL4ccqsxWkj6tPpTQhUsmQpMTzk0YEbNEByyR6OX/252R61COMtiNjYGPMVIpgF1KnqvbRbrUZzmzOwxV2BKe1ET/bB0xce0SWJFasFDXIZvczg/Rql88nCRhu83Uc+TcY/oJiRZNz/lx0BHA6SoEEU3Os/GagGgCLZbAYZWrbM7gaIp2D8VBPU/4iYP2u1K+K/DGn4yz7bkuG71,iv:H2OWar3/BBoBKORsA1IQGukY5Xvz3Mi7Ifj8ODIU+LE=,tag:n2ZlbGh9XcMXTGXiUI6ofg==,type:str]
    known_hosts: ENC[AES256_GCM,data:+LqPzA7OBJetpvWyYdX5En/LX829iXsvjreuEEGn9Q9dbklABZFeGxWt0qGL5UurgfTaKow8beVHCgZ1meAYAC8Rd+TQhYUB1lJLoMoQrL/vl8u/jYVNKPX6Hw==,iv:92YrkHYcxbl6bwYXDfnXxTlO3+jglU/0YsBO9Mma1vk=,tag:1UCT3tAzEtaUYY85SWu1Wg==,type:str]
sops:
    age:
        - recipient: age18eehnlpn44hpk4d823zfnkq72vqmf6kqhrh009uwdajneeaqzskqscx589
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsWk1iU2M5THhWSFdwSmVs
            TlNTYXJXUjUyWTVZbng2T2M0N0pXQUhlSHlvCkc2dmdkd0N3dWp6UmdidFVrQXJ4
            REkxSnJCbmo5VDQ0d2UxMGNsTGVDY0EKLS0tIFBCbXhKdjg3VXFzT0hKdW1vRW13
            QnNQSmVURTdlRng0NnZ0b0ZoSVpoOTAKuc7Mdirk1M+pnBZ6I+TtnWYXCjyKWNM5
            9A3xwFaptNWM2cNwgJkrpU+v2x9dV7rWHOXbPgvS0GGV1ECDMgSkrA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1krvwskkgw5f3ufcwgl6l2jz0emxnkn40wpup2aqhqdulqy2x99js4p5fnq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5ays3U2JCZVJiYWxJWlgr
            TGdubGFBV1E3U2N1aitnUVJwN3VDQTUyZzFJCm5kRitRSzREWWxtL0tuSG9tVThC
            WjhsRFllUUUwVjFoM0Exd1FtQ3FTZ0EKLS0tIHZySGUrcGZSVjk5M3dIS01Ha0k4
            OTM2WXZUOE9MbUZiWFVJS2VCbWFFWTgKTwdUCWghvSXsFYSeS4cbRMcUZOOwuYDO
            xadz+X5h+G2XJm29fp743hw42OV6AM3jCBqFq+QReDg0SNpvgAxm0Q==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age143yn95y2n546rlqrhgy2nzrz0w87ks7fk9dlwp3ylt0dfflczuhqrv2lmv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkczlIRzdXaFUrakU3eStE
            NzFSblhLTkltT1ZKTU5oQ2ZpZnZzZ3NUTGhRCjBGTENzYTVkNEg3Vk1heUZNVlhY
            bVJwdUVwYkdUcFBHVkFwRG1aYXpIcmMKLS0tIHdTdE01dUU2WWxPOGxNdm5GUXpm
            dWpNY3JzaUhRMWlmTHlCTWZsNysraFEKbhf8jXm+T6TK6iKEYiHO7FVMNWdz+ps1
            4bm2EpU+ijL9ia/4mGPGgcQIQGrEVPc9wmjFldxsmmWsUUJuFVcGiQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1n6eedefn6afu4e2f492xhfhckrayvp65jp7hla3x4nwj2zwz7sasw6ls6k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXNkh2Ry9ubzBJMHpYUEs1
            UndYOGwrWENaa1Q4ak0rV096NldXWHdRa2owClpNcmxyQ0VoWWRpNWJPRzE5U0RK
            bGdDT0llWklQL21vYnlmaTVYL1V3cTAKLS0tIG1tZi9ZTzhTQ2dTTjQzQ211c3cx
            TVB2aklrc0dZVTlmYXdza3NETzNtZk0KfbNYMX+wqSq1AMRbiJ2pfcdAJTBXHWXj
            j12b1fWHWGgG9Vg+cVzOwm112FOfvxy+rOb8PM/XojXR8/ynbspofQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age12g62sqmpz4pztx8zn94n8rxzklj7fj805g78m50kxu44yqy26azs2vph2y
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3bm0vc0N4b3BaYlBYbVJY
            VEN6OTMxR0pXMEovUkMvWWNtRFJCU09hUEJJCjU2UFlxOXVPNjJQUTN2aEtJUkhT
            NHpMVVNqcWI4MUlxa2lMRStmU1ZTR1UKLS0tIGNVRnpSZVpZY3U2aTdjUVRkUk54
            Z0R0dDZYYlRjc2JYZHIyS1VnMHdiUXMKRselIBZOl5TgEikH7tTYd49V2S8uwizX
            wMFd1Njkr/0NGpF2MkgBaaimkAe5ZXcNJvXerTenhZ3SgjUbZRiTwA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1tcaqw9c5sfdys359kzs2t599d2sje7sg7fha8ts42955qk9t3yss075kcn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2NUQyREhCbmpZL2hQZzh4
            YjU4V0EyOEJSSlFhTTNvVlBrUEhiaElKRHhVCmxrR3RJUG8zN0JUem1raHE2NlF1
            bE03Q3dSellmUFdCeXJ2dzlvS002WW8KLS0tIFVsYWQyd2dRUlpuOFM2bmV3KzN0
            eEMycktHVlZvMjlTdVRuMzJsSkpYNEEKLo9JckhOOp/7Aj97M5tNJrxH/Q5xWC32
            oEPG8ZNhKyfSIkfgSrKS2v0dewJ7hHXE8aQbeVG2CGlv+/ZXW3DdjQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-02T23:58:13Z"
    mac: ENC[AES256_GCM,data:csFfnzn7nJTrpxw9jwkKVoST32zuL/R+nMcZaqMftmbQVsQB0dBK/MXxXym/ls7FAQiLYNNRUcWUcLp+0xFdpIufS82mrKehLivKUEIf7DdhT2g9W7yky1V7m5dBscv+se/8UCclfn+R178IizASJS5FTOfSBkya5/NeeQLCBqs=,iv:+3Eyy8U/Pv4Sz+xQp9tGoa23VWbnFkx+7nVFUSwVaKg=,tag:xnARVK44DNTlQlBRpcMa7A==,type:str]
    pgp:
        - created_at: "2026-07-02T23:58:13Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIOA4TLBMScuBokEAf7BeG4UoiYsAe9KzhXr16v4uJ8XFQjV98gPuwxy/pTXHwQ
            Sd1SLpAGrnJ0nfeG4qTgS53DRt9+w40R3zTmZ7FGLtzWFWE8Bhxvkewx1cjLRIuG
            vYsMCuICVyCmEtDov4wRL+P3Bm7ybvvuUJPJWtipVt9pLtYV6j/3VNRROMVyHCxD
            pf8RCZi7ckQ0jxnC4liozPWVOTjRyBUzBscM0oayXIP1f0gkLVWY+LGumqh8uvxZ
            0JRZmijlaH21VnTbV9mdSf4X/WfO7gNom19xyw/3vvQ+0lYdMVzhGU9KajcgGWSG
            FsJzfjUJTJZM6LN84rmsyUFI7YrJQbY3hVT33K4rFwf9FM1qWTO3xOTgat+sa7OI
            PEPo154C+41dJIz7rmt5pd55DoL3PgJ5mrMb/SLXzvM5CLkpqZ2blWTl1bCqmlGw
            cZo6V447aEVt0YeG2MizIGBSMZGJR2VTNokKUv4usUk27oyfT8s8wdXN53d+XkS9
            LuSqSlZu7TYB/vkKQveh8BA7EDzlxOEx06qpvKE4CUQJTa0Fv1qGTDJSaFMBP8Ib
            lXb4P36lFu6fN4h+MBoHg1Sixty71is+6n3IpCzPlxZzjTm43a35VjLwZciQQWde
            /Sz26y3w27IHZDit7feF3z7qyqUHxSJOjtWPK1neKsMJFxqMeGI7lzyaL8Sm+n+4
            ltJeAb+RXPU1rJ2lQk/LC/zB0KrGOEeygNd2MllP7nLu8/7/mKaNFNvXYAMBt6pW
            gsdMrQNJGxFO0F8lQUz7s/SpZiSaQCHUuJKgg+PEIPnxGZQUmIku5sIQuzZYySdU
            ZA==
            =5D8b
            -----END PGP MESSAGE-----
          fp: C8DAE39DAA00FF97
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
