# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/refs/heads/master/v1.34.2/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
    name: flux-sops-age-key
    namespace: flux-system
type: Opaque
stringData:
    keys.txt: ENC[AES256_GCM,data:ynPUdeGace9sohTcxMR95ApQW4IszVa6Z8f48JjCKIVoLaEv+6/w3OpILoWrGTL27rm5GEoY/LWq1U5/cMmxvnAmM+tSLYZ9auxJqfBK/OCRPUfnuBGpGrQypSn5/mB6P99X1tHM9kISw24DIftk8KKxL9hQ3KtEUYzKyj/iN/JGcm2yOdFYuA2aD0Ccx0BjeWl7d+9DMZN/3WOodjQZU/VktpQ6Lgnez+clgy5+iTOQkUmCviK0Z4CYpfM=,iv:dI1OGJaR35AH6g7DAatzYW5MgkbLMnsnzbe3ZvV8VF4=,tag:cg3AI1fRe1yuH+5Ab1Lf7Q==,type:str]
sops:
    age:
        - recipient: age18eehnlpn44hpk4d823zfnkq72vqmf6kqhrh009uwdajneeaqzskqscx589
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqSlVpVktrcE9MTElGVGlw
            Wjk5Q2lOOUVORGswaERaemZqZE1OeklycXpBCiszcnR1MkR1Q2dFZXJTSU5OT3VE
            QWQrL082aVltc0ZVNHBYU2dzb2tXOWsKLS0tIGgySGVQNWVRdlo4Y3NLczM4eHgy
            c29rV0ZVc0JtUHNXcjhhQXNrQ043M1kK+TI3dkEFAbWtdJOkJ0fTOKI8khmZV98x
            YKEfBfZq+2kDd+Dm+VLCVUZd8wQSqjf9krnlDVZ6osy4mTTjNQlODQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1krvwskkgw5f3ufcwgl6l2jz0emxnkn40wpup2aqhqdulqy2x99js4p5fnq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCajYxMm1uUng2Ty9Ob3lU
            SCtrK3EwQ0owc1M4dEoxUFpieHlLQi9rNHhnCjgvYXJDa2U1L2I4WHN2dTl0eFRX
            R1czQ0d4VWoxL2lwZjZjZTBnWkxUc2MKLS0tIFRqeGN3R2tiamwxRUdJODNiWkNX
            T0tveUF0MkJSTUl2SE91cHhaYzczQ2cKbTR/tCC42Mr6E1gmoHWBdzxzBQrlSano
            G1qUjaVP304EwzytUmbPsJa71KHavqnzYOpGlWWA6QK22EJ6aidH4A==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age143yn95y2n546rlqrhgy2nzrz0w87ks7fk9dlwp3ylt0dfflczuhqrv2lmv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKK0kzSXVjVGJCU29mSHhN
            STlCTjNyVXBnWjlZa28vTW5FUVVmbGYvckFBCnRmbExyMlhXb0Y5aHF0RDhnd1Br
            TE1LTXNEVERVSzRueHh3N3NraE1mdGsKLS0tIENFNThMZ0pFT3ZVa0l6dlBLS1E3
            WUJiaGg0UkJzaVU3YmpsdkpXUGxRaGcKPunYKxd3HzgFjE3bJq9rnCJWecMUze1X
            MLiKMNVpDenyBSyLkuA26AmXJCtiMAt9ytdl/Q9uBeRjlplvUu2IvA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1n6eedefn6afu4e2f492xhfhckrayvp65jp7hla3x4nwj2zwz7sasw6ls6k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6L3ZLWnpIdU5BaHZOdXJx
            TlFBZTRJS3dKUmxIdFRsMlhGQjNiOVVtVVFBCnlIYWJlUWpIWGFBSTV4SG92b1p6
            TDFsbG1zTDZjZklyN2xWaGlHdnlpL0EKLS0tIDhrM3M4dXZqLzVHSGx6NkRqb05U
            bFB3TjVTRXZpVUtqRzZGald5L21Zd3cKaXmlbMc1pX9oK5Zu+jbCWaXMe4Nk5R9c
            4Wx1ZsQuskrzyKQ8G8Nf+emKCG3Ym3OvP8fqengCx08ID/acKUgg9Q==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age12g62sqmpz4pztx8zn94n8rxzklj7fj805g78m50kxu44yqy26azs2vph2y
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyUm92eWpEMUxsdXZVTnJZ
            RFZqbG5lc3Uvanl5TTluTEJvalFPVHc5aVQ0CmJkbGl4OXpuOUFoVWp3RmNsSVE2
            aEJVeDFDOGRkR016TnNlUVVPN09yUzgKLS0tIEZKem4xYlhsdDM1cVFuOU45VThj
            TElSZWtGN0FsczR2MWFRaU53cVRReUkKCuBAWlPu8tcR/3Z8gHaBIUQj/o8Kl7ra
            957NV8iMZasZltxxaM79K57DozoKFkiiC/zYyC+b7wXOAMuTYQCUvQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1tcaqw9c5sfdys359kzs2t599d2sje7sg7fha8ts42955qk9t3yss075kcn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIcFJUWWZORFI3MWFZQk02
            WUIxVmVZY3h2YnFEWUIrck9mYnBXcGJVemtJClcyQ2JyUmIxOVhhWmtUclp6dmdP
            bDVkYlUyQm5Wb2FZYjQ2YkpMREpNOWcKLS0tIDhBWjZwNFQwRXNyUTF2cnBxZUlZ
            Ui9pTXhzb0x3NmF3cjFFSzJkamZRTmsK5W4/bNRM3EKePI6acYQ2ROEd0pbgyO1h
            AdZsPK0WXGr9yADD4ez4J5JV2aKpLJDc4mBr59gt1p4D2hweSX4hAA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-02T23:58:13Z"
    mac: ENC[AES256_GCM,data:9nULHAR0ejrlbJ1cnSopKQ+kdl5LQHRQ8ajm6kclAUo82P62JopAnlKBHi41bS6ALN7NmDUGt48p0CYIJxJURE0hgBKFbQ/zokY/v0HssZQ6A3cmP5YsXhMqrCLXugO9mk4FrAxWVaWRz9092S3u6ck4eakO9VpgQVax6Ryuq8g=,iv:xFGSPpuYcoIZK660lUjeYtDT2VWIsMAlCQs41NFqQUs=,tag:MUP7vxgiOKnegIy8z9y6vg==,type:str]
    pgp:
        - created_at: "2026-07-02T23:58:13Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIOA4TLBMScuBokEAf+PHPElum/Q2LMZgujPHfq/uE+NAroPTCWHP98MaRDtDz7
            cF0CfjmmHoQcZNR02bmt6fLRpesJ6Vvu89UBEGcRlIbFIQKKM99D65O1U+FuR6J8
            dE1JvENUjiY7D0zaa9Qkl9Yqbdbz5+tXe6l6kvqvwWC1W6bZPxYn8jkevRueOZSj
            Dx1oyjiaVJZLgqgibs/loTkehzxu8tLZUYZBMFtCgIhJa//M2ubF26S5igYrD7aI
            /uoOBOsmPEedao0N5YYlYw94HljQ4uXi0coD8AwNeyJ+MnXdOhDhG+VDX3gTGF0W
            WU/OSBxBLh6HdbL+roMlMcp4JHPCbzhF5afkRYEzPAf/fUrAPD2AA/IXwXX8R7kD
            SXm8xvosFGJ89YAQhEpiOToYMoiJcfIOJO74zQX84pM3kmojmOeWk81/ql3CFGR0
            iYAQHpPAg8VAt1XqfxSCIfr76sQJxe5k73QHQu6zd7SXeA9EzwcVIMsp05Kr+c7b
            YynXCdA66Vqa60OClyYCsnL+dtCbQEJcq54cF1psmX1nJSE9a1lrdbwi3MDz8mXf
            WKoEzKeqULjXxm2u20b0USEbnBgk1kYnMA+YVPgMNErKf2RadMCOuQ5BhfB0YyD/
            +GXN4hu98SvbPiQwNOSxABpvjq5aM+wTykU/bY+2AvVyQFSouG5DvDbYuGJHe/bW
            H9JcAdaqmYEM8yRVbBnSyiKWnuuoCvJQqfbCaY1vnHd7G2zgCSl9ETjhyXJsPV84
            +rZ/NPxdn5hO62jA/iyDok44U+UOhUXVJkA18EACyoR9cpmJQj9SO/N2nQCIwAI=
            =CysY
            -----END PGP MESSAGE-----
          fp: C8DAE39DAA00FF97
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
