---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: sonarr
  namespace: media
spec:
  repo: https://bjw-s-labs.github.io/helm-charts
  chart: app-template
  version: 4.6.2
  targetNamespace: media
  valuesContent: |-
    defaultPodOptions:
      securityContext:
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
        runAsGroup: 1000
        runAsUser: 1000

    service:
      main:
        type: ClusterIP
        controller: main
        ports:
          http:
            port: 8989

    ingress:
      tailscale:
        className: tailscale
        enabled: true
        hosts:
          - host: nl-sonarr
            paths:
              - path: "/"
                pathType: Prefix
                service:
                  identifier: main
                  port: http
        tls:
          - hosts: [nl-sonarr]

    controllers:
      main:
        type: deployment
        replicas: 1
        strategy: Recreate
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          main:
            env:
              PGID: 1000
              PGUID: 1000
              TZ: Europe/Amsterdam
            image:
              repository: ghcr.io/linuxserver/sonarr
              tag: 4.0.17@sha256:0b5c4803f92456fb9b65bae8375716ea120b4ea17b3cced7da32b63f0085782b
            probes:
              liveness: { enabled: false }
              readiness: { enabled: false }
              startup: { enabled: true }

    persistence:
      config:
        enabled: true
        existingClaim: sonarr-config-v2
        globalMounts: [{ path: /config }]
        type: persistentVolumeClaim
      media:
        enabled: true
        existingClaim: media-data-v4
        globalMounts: [{ path: /data }]
        type: persistentVolumeClaim
