apiVersion: v1
kind: Secret
metadata:
    name: open-webui-secrets
    namespace: default
type: Opaque
stringData:
    webui-secret-key: ENC[AES256_GCM,data:Iz6Rq4+q6o1mWPEc/nOtsBtrnbCHVS1U7HKYZbTTfXPI8nhluaX+uL41DOEpUmj2r0WNL5Kt6dF8+/97zfRtug==,iv:3MsTX2MfPk6aWhtzRvhniUK+vZpZBHvQGoyBJmYkaxA=,tag:rN3q0sKkd3suxiH5jTSYpA==,type:str]
    ollama-api-configs: ENC[AES256_GCM,data:Y9nC/tMFEWVbSd/qRpW4XwTEwm6GY65nsGAFGNEVgDQsb4ekm+fCCGAudB/T/cHxB67AwUXEJTx2WvknCVLFuBnhHapVTdaF3eyafLC1+OqybIsvI1sh5F9GE0t50bXEamGYnaqM,iv:R840/ul/PQT5qwVf9nkWC4pt6qqSeHzYms18V5OljQQ=,tag:nWIO2QwMxlvEgCTbdzLcfQ==,type:str]
    oidc-client-secret: ENC[AES256_GCM,data:HeIdgum2JL7a5X/ZEOe/asMOZtOua6GCn+k/3905aJ2Mz91BrGZzr3GNl38D4ZbYqgCB2Kt3fRJyYUY5exwyLw==,iv:eMBdMx5wBYgWgMXtzEwqECJjIBMVLgJv5VC9K/PZj/A=,tag:3LvfZVMpWyrRnJk58E6mWA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBweDZ6djJxSkxwTzUyWTRy
            aTJVZlhvcnNyaFk0b2ROTWNxU25pVmVBb2xJCmp0TGJtcVE5SS9zeml4aEJnMEF4
            ODVWUDh4aFlxRXNQT3FXbkR0NlNYWWcKLS0tIFliYTJxVlkzWE5zdWhLaXVQYU9U
            aGdFMW5nOVJDVE9OYlBSRFB0WWxmbUEKu1yh2IUDazMcnMZ/38uNGTLYmVVQQg9C
            C8o231b1ibIY1j8JGhUeL163ZUWZkrYA7rDECc3QWOC/5DGUS1kZyw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1m38eu4srfs6puqtrpcazlu5kv24fd57yda4p505k9msqjwzttujs825kzl
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-09T17:42:15Z"
    mac: ENC[AES256_GCM,data:nZxKdhX3AKrCoprCFWfEuZNbrQRm+Qwrl0RsWpac+ZoKq8eSrg3ri9B2+ZItOMesLO58e05S35IlHE/0GdKKcoilr0SHwYW6rYBm7AI4oaF8jKJo8jX8PwIiVVOzrK4wmgGEGTE2ZNeGvtNBsErEBAIbkgzc0DROsJnvX5nDLHM=,iv:l/LwBSk4qfaZC2G0+2Ng2zz+b5vPt4ZXyWs5jwCiSa8=,tag:Dsq5Rb0RxkdLAMjglJ1YJw==,type:str]
    pgp:
        - created_at: "2026-08-09T17:33:14Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQINA4TLBMScuBokEAf3U5uuJUVXcwYGr+U18PWh2mY7ItlozB28+T2ERF4Rv2ky
            ung8jpEH5Mm5iywu3NqAa9U36Bz0VusnHpmx5FYtRlwNvzCachdsLccHLKQI0bCH
            FHN9rNu+Ku6/Um4kbscLeK7CxWqsqg9YxlqYrmXFIpWmy05/JvDVjAR3v8uaaKFv
            94EAjudNMCZ7IbQ/jRTzmtfU7vOc3QGZDn4xR8mEE8JJRKdXSxLd3uypd+NYsYa5
            XLhEkvSQYbtEo4WpWakukqS0HEB8vddQp1/tjDffMXxG7ZfPsreCknPxAnrFcPw/
            F4mTPVOjw0auLkC7vyk+sA8/rNQYHUW0PilyyyuhB/98ytFY1wI6zCGx81Dk0E5Q
            Fecx04bAOc+Jhu5b0edptlt7FRpLXpcsgYaZiyxuiHcYY22RuZTqm1cg2SXG6O1J
            Z4p+cHNOEu7lcGGq+BQP3vNbLoBb95WyRrctZBR3b7SDPl2iKFiB3mo2sGbT2Gd0
            r44Abu4ZhAHIlnGR9s1JY8/rC25YB4DYySdjPJFF2nmFaPYNmkR4Vvg6SVE0Njkj
            lOmOVHCvBQxY/3ibXdNmvdGz7A6vn2beKM4ffTL3nTy/zW0NmW4diwWWgosp3nh9
            k1483Vi9peJK+zMSO+cWGjvvExvQk70uZtNLiSwdGo1e/sziBBJcw/nP/l9t9/tr
            0lwBXNg/qemMLInlKWB3n2yRrmmJG2E3ZqluEoXXRbIY8KjXjIF5STK/J5rB/kEj
            LtguCkkc2gQRb8eKvt2nGor0q5dHpZPAodEL72/8X0ZahnmakLNDOj0FhuBbCA==
            =vTw0
            -----END PGP MESSAGE-----
          fp: C8DAE39DAA00FF97
    version: 3.13.2
