---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: opencloud
  namespace: argo-system
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://bjw-s-labs.github.io/helm-charts
    chart: app-template
    targetRevision: 5.0.1
    helm:
      releaseName: opencloud
      valuesObject:
        defaultPodOptions:
          securityContext:
            fsGroup: 1000
            fsGroupChangePolicy: OnRootMismatch
            runAsGroup: 1000
            runAsUser: 1000

        service:
          main:
            type: ClusterIP
            controller: main
            ports:
              http:
                port: 9200
              nats:
                port: 9233
              grpc:
                port: 9142

        route:
          main:
            enabled: true
            annotations:
              external-dns.alpha.kubernetes.io/hostname: drive.cianfr.one
            hostnames:
              - drive.cianfr.one
            parentRefs:
              - name: external-gw
                namespace: networking
                sectionName: https
            rules:
              - matches:
                  - path:
                      type: PathPrefix
                      value: /
                backendRefs:
                  - identifier: main
                    port: http
                timeouts:
                  request: 600s
                  backendRequest: 600s

        configMaps:
          config:
            data:
              TZ: Europe/Amsterdam
              OC_URL: https://drive.cianfr.one
              OC_LOG_LEVEL: info
              STORAGE_USERS_DRIVER: posix
              STORAGE_USERS_ID_CACHE_STORE: nats-js-kv
              MICRO_REGISTRY_ADDRESS: 127.0.0.1:9233
              NATS_NATS_HOST: 0.0.0.0
              NATS_NATS_PORT: "9233"
              GATEWAY_GRPC_ADDR: 0.0.0.0:9142
              PROXY_HTTP_ADDR: 0.0.0.0:9200
              DEMO_USERS: "false"
              PROXY_CSP_CONFIG_FILE_LOCATION: &csp /etc/opencloud/csp.yaml
              OC_EXCLUDE_RUN_SERVICES: "idp"
              OC_OIDC_ISSUER: https://idp.cianfr.one
              OC_OIDC_CLIENT_ID: opencloud
              PROXY_ROLE_ASSIGNMENT_DRIVER: oidc
              PROXY_ROLE_ASSIGNMENT_OIDC_CLAIM: groups
              WEB_OIDC_SCOPE: openid profile email groups
              GRAPH_ASSIGN_DEFAULT_USER_ROLE: "false"
              GRAPH_USERNAME_MATCH: none
              PROXY_OIDC_ACCESS_TOKEN_VERIFY_METHOD: none
              PROXY_TLS: "false"
              PROXY_AUTOPROVISION_ACCOUNTS: "true"
              PROXY_USER_OIDC_CLAIM: preferred_username
              PROXY_USER_CS3_CLAIM: username

        controllers:
          main:
            type: deployment
            replicas: 1
            strategy: RollingUpdate
            annotations:
              reloader.stakater.com/auto: "true"
            containers:
              main:
                envFrom:
                  - configMapRef:
                      name: opencloud
                image:
                  repository: opencloudeu/opencloud-rolling
                  tag: 7.3.0@sha256:f988f14779cbfe26dec78ea3fc2492ae063fe14a069857dd2d5a397a927fc361
                command: ["/bin/sh", "-c"]
                args: ["opencloud server"]

        persistence:
          data:
            type: persistentVolumeClaim
            existingClaim: opencloud-data-v3
            globalMounts:
              - { path: /data, subPath: data }
              - { path: /var/lib/opencloud, subPath: data }
          config-files:
            type: configMap
            name: opencloud-config
            globalMounts:
              - { path: *csp, subPath: csp.yaml, readOnly: true }
              - { path: /etc/opencloud/proxy.yaml, subPath: proxy.yaml, readOnly: true }
          config-opencloud:
            type: secret
            name: opencloud-secrets
            globalMounts:
              - { path: /etc/opencloud/opencloud.yaml, subPath: opencloud.yaml, readOnly: true }
          tmp:
            type: emptyDir
            medium: Memory
            globalMounts:
              - { path: /tmp, subPath: tmp }
  destination:
    name: in-cluster
    namespace: opencloud-system
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - ServerSideApply=true
      - ApplyOutOfSyncOnly=true
      - SkipDryRunOnMissingResource=true
