---
controller:
  service:
    externalTrafficPolicy: Local # To preserve the original client IP address.
    ipFamilyPolicy: RequireDualStack
    ipFamilies:
      - IPv4
      - IPv6
    annotations:
      io.cilium/lb-ipam-ips: "10.0.3.1,2a02:a469:9060:3::1"

  metrics:
    enabled: true
    serviceMonitor: { enabled: true }
