---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: lldap
  namespace: argo-system
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://bjw-s-labs.github.io/helm-charts
    chart: app-template
    targetRevision: 5.0.1
    helm:
      releaseName: lldap
      valuesObject:
        defaultPodOptions:
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
            runAsGroup: 1000
            fsGroup: 1000
            fsGroupChangePolicy: OnRootMismatch
          resources:
            limits:
              cpu: 200m
              memory: 256Mi
            requests:
              cpu: 100m
              memory: 128Mi

        controllers:
          main:
            type: deployment
            strategy: RollingUpdate
            replicas: 1
            annotations:
              reloader.stakater.com/auto: "true"
            containers:
              main:
                image:
                  repository: ghcr.io/lldap/lldap
                  tag: latest-alpine-rootless@sha256:75035f094a2739d5c29a4f7eef3198adfa229b78c2d91624d1a62ab26614f9ee
                env:
                  TZ: Europe/Amsterdam
                  RUST_LOG: debug
                  LLDAP_LDAP_BASE_DN: dc=ar3s3ru,dc=dev
                  LLDAP_DATABASE_URL:
                    valueFrom:
                      secretKeyRef:
                        name: lldap-cnpg-cluster-app
                        key: fqdn-uri
                envFrom:
                  - secretRef:
                      name: lldap-secrets
                probes:
                  liveness:
                    enabled: false
                  readiness:
                    enabled: false
                  startup:
                    enabled: true
          bootstrap:
            type: job
            annotations:
              reloader.stakater.com/auto: "true"
              argocd.argoproj.io/hook: PreSync
              argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
            containers:
              main:
                image:
                  repository: ghcr.io/lldap/lldap
                  tag: latest-alpine-rootless@sha256:75035f094a2739d5c29a4f7eef3198adfa229b78c2d91624d1a62ab26614f9ee
                command:
                  - ./bootstrap.sh
                env:
                  LLDAP_URL: http://lldap.auth.svc.cluster.local:17170
                  DO_CLEANUP: "true"
                  LLDAP_ADMIN_USERNAME:
                    valueFrom:
                      secretKeyRef:
                        name: lldap-secrets
                        key: LLDAP_LDAP_USER_DN
                  LLDAP_ADMIN_PASSWORD:
                    valueFrom:
                      secretKeyRef:
                        name: lldap-secrets
                        key: LLDAP_LDAP_USER_PASS

        service:
          main:
            controller: main
            type: ClusterIP
            ports:
              ldap:
                port: 3890
              web:
                port: 17170

        ingress:
          tailscale:
            enabled: true
            className: tailscale
            hosts:
              - host: ldap
                paths:
                  - path: /
                    pathType: Prefix
                    service:
                      identifier: main
                      port: web
            tls:
              - hosts:
                  - ldap

        persistence:
          groups:
            type: configMap
            name: lldap-groups
            advancedMounts:
              bootstrap:
                main:
                  - path: /bootstrap/group-configs
                    readOnly: true
          users:
            type: secret
            name: lldap-users
            advancedMounts:
              bootstrap:
                main:
                  - path: /bootstrap/user-configs
                    readOnly: true
  destination:
    name: in-cluster
    namespace: auth
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - ServerSideApply=true
      - ApplyOutOfSyncOnly=true
      - SkipDryRunOnMissingResource=true
