---
# yaml-language-server: $schema=https://www.schemastore.org/kustomization.json
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # Temporarily disabled until restored CNPG volume is rebound and cluster is healthy.
  # - application.yaml
  # - lldap-cnpg-cluster.yaml
  - lldap-groups.yaml

generators:
  - ksops.yaml
