# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/refs/heads/master/v1.34.2/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
    name: lldap-users
    namespace: auth
type: Opaque
stringData:
    user-0.json: ENC[AES256_GCM,data:YZKgDMz5aGWapn5Ij70qWXj0HaRXaWtQ5eIEQY8llRX7geW1u0kgFn+1VNsB/uDFaocHiGA15p5+vjDHYT3YSf38+47Wya4HrcklnpogSDiloByn7bt9gstU/aA69iLs2GZ5kdrI1tyRyYHpxoQSiPCcb73Rv3mzgIcl8w0sjUSmmnDFUf0q7eq9voEswbApnT907HdwNhEz6qVVoufsuI+XxBSR3hFuoK3OGahYLD4OZtjYXo9q4iF5czTzumB4mpbZY82aglHXlmZbwHFAt/ohaufZZw3V9x48VhhLtbIIxqXu/uH7j0y1wuePg4WZfqTJSFrZD4LjWWE40x8APtIEu+8BR6THvw3sCsNRwneh50NSTyktKcY3iY+8vwrzcbEqIWjTtV9PyOSXpKe6+mzA1ToQmlvtG6UErPAk,iv:94Be76Tqbbu8acqMFQ3QxZIoMLmc8or8yPqMv1hJ+fo=,tag:cHDYgEpExuKeyyoKM6OugQ==,type:str]
    user-1.json: ENC[AES256_GCM,data:6nYilwgwj4sU4dwNWff4RVU6o7LN0Ov7eXk/Rg+3UBY3tR8xHdR73iL/SYE7FNlAD9q+SXapJCEvH4KWfNJX7oaq4Qx57INPuEstWLKsDNHNNquOpevQBVBJEgQ8sHeM7xYG5uzL5oot+KsuEp2m1klXUr9ISFc3IVAoyW72BCcc0mAZeRHVTVuS6L3l15jhORkWUT2w3AT3tXY/n3jtR2DwzTPmNcgzUfkBgEj+Nw7KzYDuHzQr4g7P6UGIvlLOOxJLCm3KU2EjrGoV4O9AzwoFdARRnXxRs/maFpcwIcC2unXKwQ==,iv:8iSeRw9ZaXH4Po9sxtaSRLJAlvG4wNe/Y7xBp4GpNd8=,tag:7AhloZZI6dSAIbMrQMuQ/A==,type:str]
    user-2.json: ENC[AES256_GCM,data:Zuktv43hCef6ZrQNcxVcxeD6HQvQ8fosA/ZijEOtI7L1mWowrNm9vyUjo93IvgsAKMG4MV84w8D6+ziOC12yEGpPJjZLmFcmnOQndB35DeVgVLBwq4N6Nn2ebuwEEt7oiqS+xlEjhwKuEG28G3X/NKN9EDplY2+0nlS4TF7g9MdpsgADt2yh+uA5wW3bfZrasDtWQBNXlIalzJPitNwqYUdefFzk2OM4,iv:un/JEJlDe9Rz/hjMyp7I1dr7JkfDHfro8QIX2UB0Y5A=,tag:HYL3A52I1krW0JJNzis3Ew==,type:str]
    user-3.json: ENC[AES256_GCM,data:LJj8PG1UQVyuvuQku1QZdg96Ie7O5OgPHQ54j9lZfTPIJ+SAzWaChg+IPoNjn6K+qClLxT0yIu+UlfAL+fuwwoD2mUVw3S7o/PH0pscrt58lr8cU1Ek8e5Lq/ssmNyk8PRwGu6fa7il/YWR/OAyPCE4yHfVdKT0oJgMx49q/ptoJm34lxLdC5LjTpNATwoIZduJtSLWrwE/GBAmtl0aEzib0yNS+7L3rpY/Rc515Sp87PWZvoeB5HnHeQX5cq0v5Ft/4TwGTPkTOCszOVPI56sBsaw==,iv:nZXcdDDNTR2JgImoGfdIndijOF6QG4DPhF82tuaOE4s=,tag:IMJKQulrJlrYx/hnLQbxsQ==,type:str]
    user-4.json: ENC[AES256_GCM,data:QWY74qW+nCUfVWXKkveutO0TuiC53K7bppCuPd36VKoY6hZXEsnC+rIjM+Icwj3UzxmISMeau1QX64rWdX7gzOdxw2lI0j+NEZAPiJg506QGyjqOoe+hen0dFZcsTuOLBUi7fYnwceDglAmSGROhKQppPZC5d5aqoIcDlqcFmcTc96bwl2SrEdwpZWU+ZLTTjSQ7dMWYPZZSWQsY8MEqrjbhm/nJ51EPxfNjzlURBEEk4u+7WhXn4VG7LKSdTpCPpqc9zi5TgHyY25O1dQ==,iv:uIV7DwAj4Z4w8wIolIb+wOf3ypwB7yjmU2/M5Xa/fZE=,tag:tYc7eG5H2oA4oyqkq+49nA==,type:str]
    user-5.json: ENC[AES256_GCM,data:uL4dlVToKeTF3CM0DFlJ4NtD2qJ714x/fm+ZZsQot5Uwtp/bx5Z1denoimFkXw3aaYF2Evz51u4zt61ss0mGEmt3tmSU8EfZYRq8sGEseaY0ux1jVTJIgOS31lWTL/QkZQZ4W87tVhKjRPnwdZyQkWvSau+HACRBBK9/JW8NgE6akU1+NSvIk3FcBbCJXeGA71jrP+tq5uExA9nNA6FcQi5tQA==,iv:/lfpUxuBnldp+AlhyThTl3fyO1aUJrQ+k2dHa6+BOM8=,tag:/Lm1PrD22rKX/Dphxxwmtg==,type:str]
    user-6.json: ENC[AES256_GCM,data:Jg3eVPk5535W3qP/q5OsAXxPBbHktOMpqpOCftiBOaD212nMmvdgeFeBgA2Ih1tNhnsdmGddovWDXhYxwYh+gyvbWtuOlTrGaQph/kwSyyT6NztBBBIDy2Y6RemxgDPnj3WGjjQLt93rLl+UP2DNxwdeD6KUlBYHZeajqjl7inqQpSXzWHe7dFru30nYcvEt4RNwb/mKnXAzd7zyad6fKI4Lik0touQin1sdMtMGera2r9LU2DyESVGTL1EdyFxpbycfDwXCo8RdZSLVyNXQJ/EwdusTJXP4cYQb5aK1JMLOJZmfBiD0QGzJlDGiDoBfP2SvjVYKD/kLfxmHBclJCr45LWbIHQRtDVhmjJIIlY8S7kH9whLY5KMRb1VsIi8ucrxN7e24Qy8=,iv:gfkEwek/UeiLCrgStcWu8k2UZzqvzXY0BF1a5lLJIw4=,tag:dVo25QErjs9kz0CLuUTGwg==,type:str]
    user-7.json: ENC[AES256_GCM,data:Ug7oYAc4XgPR/HBIulAohhSC0C/SzhtpAJMr1JBunrEBGzxYgStFt/cRBfNCEMdNTzEpFGUofniy0aLVK84wlB/stvIIA58DtlMFhCknVRD+xge7A7hPg9/xjiXLIkQMP3zJoASY5BMuFXpQaa9ftxPnmbL2qaaUcpqLDDWu4XLDp4ow/b1evkba+1wZVmVXMPie21Cd8rc4qet/ki80jw0Gj57QUnNAaxAZVijrQcVJ1I0U,iv:F2J1FCuSRs3QBI6FwPgHZlnqjlqFIB450pBz01jOorg=,tag:PVNptXFdzUQkVTPwjN1hMw==,type:str]
    user-8.json: ENC[AES256_GCM,data:ItyjCGoDR9LSogAwKe4hrgUOe4eCiPPpCEjauh7uDQ9wY8IqqF7E3rB2x9A7js3RHf2G0laVTSHOOviXIi96QJxVcQ+llsTb8ul6RWyvzwSZUWE6O/CTylCVsBeOgpLa3+qh+c9wm79BTopKyk5sxsMsEh4KZS+fFGaGqhV5v2uitMXSmjHuJkTzljkrSo2AejNJdQhtCOAWOYxMgofWdm0K2xFgEGqtVoL3wHWz5FPeRizUufaN0MNE9Rpa,iv:SV73rFGeLpiQ1PXFhcHw3jerpcHyHoNT61M6XQbzMTs=,tag:h/uJAaeGfsbDHa5205kGxQ==,type:str]
sops:
    age:
        - recipient: age1m38eu4srfs6puqtrpcazlu5kv24fd57yda4p505k9msqjwzttujs825kzl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmY2I1Nlh6WmExZ1p0NFF2
            TFhJMW1YRVg4MmRnUE43NlhzcnY5MVRLd1RFClNESG9uaWpUZWtKV2t3TWRBZCtt
            SVI3aEVxZStkNmpoZEJJdklVRFNuVW8KLS0tIFlieVZBMW0rb3dNc0w2Vlk2b1R1
            WElKTU9BMWE0TlArTEpjaWRKUjJEcDQK6EEj3oBfl1zrW//DKOq3cSnYYS30sgrJ
            kkLf/GKC25qzMVokFARhrYNaoA0mVjwpc5L2yx2od6jmDuhBQAWm2Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-17T19:22:24Z"
    mac: ENC[AES256_GCM,data:ZFcsW1211qFWlkRcV00afDyLEmeoEaOPPgSPpY6DmEhSZ0rMnZXDWIm7t3PuJHD127DK/N/fLmLv5iIsDXWaFt68cNjlbcEilA3P0thEcnSV04CybuiDp3Z/LgARJvu8nclebdktXY08Hq/Gyk2tjM+SWCdGs+pcacvIOMnLCAM=,iv:3I0Y5cXIm7ihvFvlG6WPs30rqUxIUSi9RECx0JE5MfI=,tag:iNPDldyN6Gjqv2t6QGl6xQ==,type:str]
    pgp:
        - created_at: "2025-11-23T23:00:16Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIOA4TLBMScuBokEAf/fI7XeqfvfWf9FfkAle1FNEau4/zphzVNmvVRCkhiYZkx
            xCfgaL3zWsLXfQf7w49SvONxO5aNYqZFUZm0IjsiEXmZRrg6Q/BiXXEWi5ySZ7Os
            gzTBofNw33EdwaLShn5Oq24HjhWppcTbMO8Uoe1EJFObGKLcmpmYAdCdZ8qESMpx
            A1aiNoo4PzClzAvBFTJaFqvUb7VuQqEGALBNdauTJ8T6XvLpnfRJceLLMrh4eOtD
            mzIPo7Uhy7XjdmPPj+UPYtnbraRzhIJPcu2RwNzOGuQjz755RWLeiSnJNboXOdav
            liTXu5SwCVL1awPnDgAUfqCs++rPeGJFApb7KYQsPAgAjo7k+0BdZoqiE9/A5vi7
            F+HjiruvXCdXvgCb+18U4mnJEwDCPUCUdK0q/mB9wrfh9lMviI+kjMvIDgaovKI9
            s2Idkcom2EpGCS/0Asv0dqLZT/wVNmnLKWB0tfHuCIk/xEsf51505savVJ70Y8kX
            UOQHTt03cw+7+g0GuTc07MClkBAgoX6Voh2QZzfJ1gzg3PggyQtGcekKRk1g9YJa
            EwJux0k/+b8cLjVjp8dCHN9OGq3vlTp7ztt8uyzUbx0LLX8mE67h7yRJy4xC6dz0
            2flHAZxLuS68s8wvFvDhrztMLrMR/Jq2jyBtnAqShXTJuUNMz+mo+PsXmZPUcgTR
            ndJeAdpRM7/Lgu+sUHCnqDxHKoGg7OeqXfAekrttnwPeAzcl08/aF1n+8YG302ML
            EJNTEnu38S1zCL6kshOL9pXDW8/NM0GlZaKJ2SwO0zePMZxNuIM23Jj/X5Q99QSx
            bA==
            =I3n8
            -----END PGP MESSAGE-----
          fp: C8DAE39DAA00FF97
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
