---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/values.schema.json
defaultPodOptions:
  securityContext:
    runAsUser: 1000
    runAsGroup: 1000
    fsGroup: 1000
    fsGroupChangePolicy: "OnRootMismatch"

controllers:
  main:
    type: deployment
    strategy: RollingUpdate
    replicas: 1
    annotations:
      reloader.stakater.com/auto: "true"
    containers:
      main:
        image:
          # FIXME(ar3s3ru): use a stable tag once available.
          # Also note, this version is not available on ghcr.io.
          repository: docker.io/fallenbagel/jellyseerr
          tag: preview-OIDC@sha256:9f3195998306da6548fc3b2420d114dda64a6e904f41e911168788fb410a7972
        env:
          TZ: Europe/Amsterdam
          LOG_LEVEL: info
        probes:
          # FIXME(ar3s3ru): find a way to enable these?
          liveness: { enabled: false }
          readiness: { enabled: false }
          startup: { enabled: true }

service:
  main:
    controller: main
    type: ClusterIP
    ports:
      http:
        port: 5055

route:
  main:
    enabled: true
    kind: HTTPRoute
    annotations:
      external-dns.alpha.kubernetes.io/hostname: requests.cianfr.one
      external-dns.alpha.kubernetes.io/target: gw.it.cianfr.one
    hostnames:
      - requests.cianfr.one
    parentRefs:
      - name: external-gw
        namespace: networking
        sectionName: https
    rules:
      - matches:
          - path:
              type: PathPrefix
              value: "/"
        backendRefs:
          - identifier: main
            port: http

persistence:
  config:
    enabled: true
    type: persistentVolumeClaim
    existingClaim: jellyseerr-config-v2
    globalMounts: [{ path: /app/config }]
