---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: akri
  namespace: argo-system
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://project-akri.github.io/akri/
    chart: akri
    targetRevision: 0.13.8
    helm:
      releaseName: akri
      valuesObject:
        prometheus:
          enabled: true
        udev:
          discovery:
            enabled: true
  destination:
    name: in-cluster
    namespace: kube-system
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - ServerSideApply=true
      - ApplyOutOfSyncOnly=true
      - SkipDryRunOnMissingResource=true
