---
image:
  repository: ghcr.io/dani-garcia/vaultwarden
  tag: 1.36.0@sha256:d626d04934cd1192ad8ced1adb975099fca78cec33ab467d2d3c923cde7f3b0c
  pullPolicy: IfNotPresent

# FIXME: review these limits
resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 128Mi

replicaCount: 1

database:
  type: sqlite
  wal: true

service:
  type: ClusterIP
  httpPort: 80
  externalTrafficPolicy: Cluster

strategy:
  type: RollingUpdate # Longhorn volume is ReadWriteMany, so we can do rolling updates.

ingress:
  enabled: true
  className: nginx
  annotations:
    cert-manager.io/cluster-issuer: cianfr.one-acme
    external-dns.alpha.kubernetes.io/hostname: &host vault.cianfr.one
    external-dns.alpha.kubernetes.io/target: in.it.cianfr.one
  host: *host
  tls:
    - hosts: [*host]
      secretName: vaultwarden-cianfr.one-tls

persistence:
  enabled: true
  existingClaim: vaultwarden-v2

vaultwarden:
  domain: https://vault.cianfr.one
  allowSignups: false
  requireEmail: true
  verifySignup: true
  allowInvitation: true
  showPasswordHint: true
  enableWebVault: true
  orgCreationUsers: danilocianfr@gmail.com

  admin:
    enabled: true

  smtp:
    enabled: true
    host: smtp.gmail.com
    from: "nl.homelab.ar3s3ru@gmail.com"
    port: "587"
    existingSecret: vaultwarden-secrets
