---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cliproxyapi-data
  namespace: default
spec:
  storageClassName: longhorn-nvme-encrypted-3-replicas
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
