apiVersion: v1
kind: Secret
metadata:
    name: cliproxyapi-secrets
    namespace: default
type: Opaque
stringData:
    api-key: ENC[AES256_GCM,data:7V4prnCjOHa+dEaa7zaxX9y9awQss43ZJyQBJOWhJJ3KxwMQvAD2lGW0MA==,iv:C9CBITmMaOV/qHT/zXQARN6GeXIvAaQ9xrIGWrecnBc=,tag:1cV796oibXtM19f16oZQ/Q==,type:str]
    config.yaml: ENC[AES256_GCM,data:IiQEu0H2IWCL5gNR199ieJ7OKFH+2drKcOmvPucZxw4sQI6DFP9Lc7sX21aLXihts4YUS7FGxZSPIqkgzq2QzDqWoSO2Xi9guXALyuu5RFFqZhfw7jOrpDT8kE+H5rSE0DfsClEt99EyJTGJrnDwTbFZFMcHhI6+T39T7hGtvYNjBiBC5UiPECKhbzxvIcSYY+Kvtj7D8WlPsJCPnznSI/yupjgD6Y7OiwGfHK8Bj8zLYWceL9e7To//Wl2EcZJMYtxHVZsSp2Q48zV4oLaaNCayMaOlTh5qAgcIZqypCxyr7G2QD1zqyc4QuMxNT9yVyvMj5Em6CUg7Bk1Ev74CLnnuWAyHJstX0CnIFYJM1WW/FO2otrS4vphXEUTuAWJQTQgcXCYKFeeW+HW56cvkAkLEKc6ur194dBKnAc9sn+wKhrFx8piZaGbM2QpdC3w=,iv:zkZuuxpiB+1232/MJ5xbBiym+BLmOJqm+w/k7TwGD4U=,tag:rVeI3/loQuQhPxzvvIl7UQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvZW9pSWtRS3lmZENvVFZP
            R0JFYnFMeWpTWkZTQm1SdnVqS09wQUpqazJjCjVhVSsrNXdzOGdyQ1RWOXBOQjRm
            Y2xHTmR6Ujd3WXdFNUxUbHhIYy9LNmsKLS0tIHd4UHc1OXpha0trOHgwVGJwWG5w
            ZTREY0hTc2VBdWdEcFBqRmlwWnpTd00KmqN0+GpR0d6wDgx0hC2MPC1J4n2kJbVU
            qUPxxz9RRL7C1NqWTNpLlH0gVdZZcFHbaGCl1+L/qol8jEd8Q5vmRQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1m38eu4srfs6puqtrpcazlu5kv24fd57yda4p505k9msqjwzttujs825kzl
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-02T18:50:27Z"
    mac: ENC[AES256_GCM,data:TuNBogNBN/fYWBwoa+0BrauZNlVdfimu1leCd1KzSw1F3p49Bh6+viauvgE7Md36amach4krLwsJCjynM0qITruG6ViyAppg/76NqcMzxPp9vLHna0K4jHSKX7Swx6Eyiic3WSPZH48akuQNG3YiOfwLLqjyDqnsY/LcTbnZIWE=,iv:ABPdjpNxD8a/F7ATidbIotUyYyk8G2deZo7aNFNxH18=,tag:R5WiSQLLYSIiqfNE820Ukw==,type:str]
    pgp:
        - created_at: "2026-10-02T18:50:27Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIOA4TLBMScuBokEAf+NQLNtU59heONWU5FAmcYua7CgaY5KxG5/XYIrxpSVw5W
            TVCBBJiLwlYRJdc59S3ivb06Fy+guPayJQFhrNU4cxkKN1bcIQEHWsaqQpMHfMXO
            rQdx0U84As17a4mUXLqXgEG2u6xF8uZ4cHsyiNYLtxCDD2QHc5grM/vZPGLeuREj
            Y2/9wLT3x5+K4sMg8Ghc/unE4FDlBPbNLxw8ZKyphrA6VeRiYSg/FlKDQXYq65kd
            Y47g4uhwe96FD7NZE3O6hggqZO/ECzX14pXnhugIW2wilg+6YAOnPN4tdo+068tD
            jFvOwqfagOcikLSnrAOoelkV6m6y1po3mcyG51ddgAf+OTtKLXAYbzVLfjS9dw2I
            JzppVrz4CGfm/g1Nuggd3L3lBNYdfUW7Rr9SwLkTkbjD65D2Rp1nKnvGWz1BtxWW
            8CcdU+ew82v0oOOQaiUw3/h2hMINAS2X/SeC6C4LDlGRip79z7/4egWQqK/w7Ewx
            gA02gr9iOxLGTGbxXxSEPDTwBz+/mMlQSbu6LKU8Js/W4FxgY6HSikPcZQxJHYUd
            E34wgh3npWwVgcRRhhtZQ98vUY0TOo3zlas4ol+CEmrYEqPdtGPLpJGpEb0F7fcq
            3oEWSOiM6K8+lMpGHoduInPUgkUz9iRLZdu72Hggm6Gcw482l9EJHRTFnatGOm7Y
            dNJRAaExCi/HUqQ2a9K59R8ZgZtRCrpydoHa3nTH0iIpRLn2NY5w6X50MRmY4BfV
            zCie/pRpfH/aMCG0Tq4GZcbTcxEqlgcsavkfv/T5wHZHxiq1
            =eTBF
            -----END PGP MESSAGE-----
          fp: C8DAE39DAA00FF97
    version: 3.13.2
