---
apiVersion: viaduct.ai/v1
kind: ksops
metadata:
  name: cliproxyapi-secrets-generator
  namespace: default
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: ksops
files:
  - ./cliproxyapi-secrets.enc.yaml
