---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: slskd
  namespace: argo-system
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://bjw-s-labs.github.io/helm-charts
    chart: app-template
    targetRevision: 5.0.1
    helm:
      releaseName: slskd
      valuesObject:
        defaultPodOptions:
          securityContext:
            fsGroup: 1000
            fsGroupChangePolicy: OnRootMismatch
            runAsGroup: 1000
            runAsUser: 1000

        service:
          main:
            type: LoadBalancer
            controller: main
            ipFamilyPolicy: RequireDualStack
            ipFamilies:
              - IPv4
              - IPv6
            annotations:
              io.cilium/lb-ipam-ips: "10.0.3.2,2a02:a469:9060:3::2"
            ports:
              http:
                port: &port 8080
              slsk:
                port: 50429

        route:
          internal-gw:
            enabled: true
            kind: HTTPRoute
            hostnames: [slskd.home.cianfr.one]
            parentRefs:
              - name: internal-gw
                namespace: networking
                sectionName: https
            rules:
              - matches:
                  - path: { type: PathPrefix, value: / }
                backendRefs:
                  - identifier: main
                    port: http

        configMaps:
          env:
            data:
              DOTNET_BUNDLE_EXTRACT_BASE_DIR: /tmp/.net
              TZ: Europe/Amsterdam
              SLSKD_APP_DIR: /config
              SLSKD_HTTP_PORT: "8080"
              SLSKD_NO_AUTH: "true"
              SLSKD_NO_HTTPS: "true"
              SLSKD_NO_VERSION_CHECK: "true"
              SLSKD_SLSK_LISTEN_PORT: "50429"

        controllers:
          main:
            type: deployment
            replicas: 1
            strategy: Recreate
            annotations:
              reloader.stakater.com/auto: "true"
            containers:
              main:
                image:
                  repository: ghcr.io/slskd/slskd
                  tag: 0.26.0@sha256:ecd4026d4f8fb504e2cc55323efa2c1f5b56d20d3686b018249cc36b48ea17a6
                envFrom:
                  - configMapRef:
                      name: slskd
                  - secretRef:
                      name: slskd-secrets
                probes:
                  liveness: &probes
                    enabled: true
                    custom: true
                    spec:
                      httpGet:
                        path: /health
                        port: *port
                      initialDelaySeconds: 0
                      periodSeconds: 10
                      timeoutSeconds: 1
                      failureThreshold: 3
                  readiness: *probes
                securityContext:
                  allowPrivilegeEscalation: false
                  capabilities: { drop: ["ALL"] }

        persistence:
          tmp:
            type: emptyDir
            globalMounts: [{ path: /tmp }]
          config:
            type: persistentVolumeClaim
            existingClaim: slskd-config
            globalMounts: [{ path: /config }]
          config-file:
            type: secret
            name: slskd
            globalMounts: [{ path: /config/slskd.yml, subPath: slskd.yml }]
          media:
            type: persistentVolumeClaim
            existingClaim: media-data-v4
            globalMounts: [{ path: /data }]
  destination:
    name: in-cluster
    namespace: media
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - ServerSideApply=true
      - ApplyOutOfSyncOnly=true
      - SkipDryRunOnMissingResource=true
