# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/refs/heads/master/v1.34.2/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
    name: slskd
    namespace: media
type: Opaque
stringData:
    slskd.yml: ENC[AES256_GCM,data:KkkugvcDqoWxMtQPKszIEbBAzInHOxGxD/1D1N3QcaBotyJt5cK5gWkYVAz2S3jSqhkrtHzFJNMUoj7YxfNg7ANFIKCT9dfhIo2p9xdwrT10VbE/hpr3ewQEApFPM1iI8MzSUJKwwmJktMiSoqggMytFhOHvY6K9VC13QT4ZXPpb4+8Yn8rTyhC+wtMMkRTXWph3XaZZzD+XPvkILqPhhsNq0ZbBAq1ep/ArUcVWm/L2Zvk2crME3BDV6lVdoP7v7Hwnwq1YOKBcelzotyh9MX1f9ZIcy2tK5YZKWq/7aMBt/jC5p6CkVGlz+u28TTARRWcdEMCNui+0tnUqq15ZudDsoLTvnaGR2ViagZXyDYuOatPqxMMEQdlsye0duT95QU7boHNwy5sBDTIgJ0/XO7Gpss8boP5MyODkN8RCjCwOcjpT+z0CiDtnqJjp3vdsBDkk2n9ccmEqSdSMv1QQuOjDF4hj6CinXe32CKE7TB0JCZNkpWco8Z9WORnfaZlkhyqI/4O3dAy7mWr5A9ivsCyvwbDaz2GgAHcoXGWf3sbWu83YDTce57Az/8IAUxWf8j7sFw==,iv:yY1UVEEODo1uIFp5Kd7MD9yAsxN8nbbomEj18DWnR6s=,tag:KAVfnFV5WGCww4PME75N9A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoRC9HUWxSdDR3V1I3QitM
            bUpiL1FzM2VmNTRIRWNOcVQxempBZUp3VFhjCng5bnYwdVlMd0MycXNNOEs2dXNo
            MDF4K0xTWEVMbUMrZFRYL09kYXdOcjAKLS0tIEhpQTkvNmxnQnZkYXBMeXZ5L3V5
            VHl5ZEVtU2gxOXBQLzVoNVBlSGwxTk0KO/BSpKIokBYRMqg0k9tEIG8EvuxTpu9Z
            5NK4ZTmuLzpYdJwKMCEbdDr0wkr2tnQ0PY+eGCVkMhX8knATO/tVxA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1m38eu4srfs6puqtrpcazlu5kv24fd57yda4p505k9msqjwzttujs825kzl
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-22T23:03:07Z"
    mac: ENC[AES256_GCM,data:a1Lle+wEsqHnzSp21WvVIKDhoh7KA57SfPhOEPEn5xN95uN7jt7OJrk2lAaO1pY73pC/aTigWM0OZ5ebxIJBN/0p59z7pwyylH+WlW/DrnaLJAp9tMp8DhpCdBXRnCFogkf35hgj04qfNZiD8wjTDSYvFiKi2XQZvZdhVf6e3IE=,iv:NF5Eo7G8tr7E2uCCY3ue0VY3DJ8jGsvvbgbeoROVMZ8=,tag:fzfl5XBKWhBtCIzsQewX4w==,type:str]
    pgp:
        - created_at: "2025-11-30T21:11:26Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIOA4TLBMScuBokEAf+NARnMLGr98bkj4VHf52NTs7Kew3Ai0lIDwdkPanVXzdi
            s7oOCHBIxcWjY65OPZdm0FWPwzYNpLyHLdThl3Ru9K1MathZ4nkqAy4xgn0jZG4N
            lwBtqLF4MSM93LXuXGlYAN58ZA+9mxHkmn2Lz9Xvki0EDW1U5S1eCGpnTn50PnV5
            Zwb1VHV6tflI/Z2Bcg5AdOxc1JYyX9AXgjKvYTn6ueMtZeepJd2kUPNssEwR6lo2
            W9vhdwktGEaGzCLxcqBC5q6497nNCBcSKmQ8AHKoa7/GKB+SsKhfzVB176gUEFfJ
            s3Tbxlv1ZSEP6qRhQG8E7oRucdYbytzBJqFPsm+7CAf/R0lHhK2NzrtsaxMvXgUQ
            UbuNuwhhkfjLcuAx2PqyLDZ+jszE5mON5vBQwEZC8QpiEBzSRFpBXM1potme3AHo
            W5jeDjozwBjR+dnvaQQ4VJd2R52+PaL1FrR1sE1n1n476XHGEcI/daySm0fCgMbS
            Jg+9zp0nVk+vtqmZR9vk2LqfFB6uxIwyXF6uOewkn/E++EwB1wEvhxykjn0euIdS
            S0jpiq+gokQ4F32p4Q0l7N+oo+LpcCmw55oxFpyJwa+gCujqVqptpEOTbA6fogcq
            UK2O7JtDXaR6wjrRi3sJr5XtLfuyeL1jroT9KiBPegVa5U9J412j77Y/1L8Ur58+
            CdJeAVJbGm5B8gXRrIqkWXzajZ9xTUb4TYOnIVjcaOyvQqI8y8G38vacT+RTx3Rk
            0IyuGRiRspgVcCjuGhNRticJEeiWBwYEBPCqDqCvuL59ltgCAmHtzncfz3r/gae8
            7w==
            =u1sD
            -----END PGP MESSAGE-----
          fp: C8DAE39DAA00FF97
    version: 3.11.0
