# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/values.schema.json
---
defaultPodOptions:
  securityContext:
    fsGroup: 1000
    fsGroupChangePolicy: OnRootMismatch

service:
  main:
    type: ClusterIP
    controller: main
    ports:
      http:
        port: 5000

ingress:
  tailscale:
    className: tailscale
    enabled: true
    hosts:
      - host: &host nl-kavita.tail2ff90.ts.net
        paths:
          - path: "/"
            pathType: Prefix
            service:
              identifier: main
              port: http
    tls:
      - hosts: [*host]

controllers:
  main:
    type: deployment
    replicas: 1
    strategy: Recreate
    annotations:
      reloader.stakater.com/auto: "true"
    containers:
      main:
        env:
          PGID: 1000
          PUID: 1000
          TZ: Europe/Amsterdam
        image:
          repository: ghcr.io/linuxserver/kavita
          tag: latest@sha256:93b8d00423b0259805beee3004acd9d70af41e6a632a53547abfad0ca6a0ddaa
        probes:
          liveness: { enabled: false }
          readiness: { enabled: false }
          startup:
            enabled: true
            spec:
              failureThreshold: 30

persistence:
  config:
    enabled: true
    existingClaim: kavita-config
    globalMounts: [{ path: /config }]
    type: persistentVolumeClaim
  media:
    enabled: true
    existingClaim: media-data-v4
    globalMounts: [{ path: /data }]
    type: persistentVolumeClaim
