# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/refs/heads/master/v1.34.2/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
    name: authelia-oidc-secrets
    namespace: auth
type: Opaque
stringData:
    immich.client_secret.key: ENC[AES256_GCM,data:PoRed5jUWeBQf78Wm8RlK50fC3nWMdlZ4b8QitXEENxonrPU3oUWe8H9f4Dn+9kc8i/Jx38UXKmoEsP8MmDIGBNRPyLsS7cO,iv:NdRwkDibamAGiHW42IO1WdcsxvD+pJEidLrOZFW10rk=,tag:i0L8mkuP7cE1Nozsedowjg==,type:str]
    hass.client_secret.key: ENC[AES256_GCM,data:8J1T7QqiSbUzjHrjLCOzVxOHFY2qTvSp1rwtwqLM6c406xluSemPVHO+vSfeYllkx3wIEF07kbolvYVbKrV7ZsGVRSLvZ3zB,iv:MvEGyrNDWjcvDatt1zd2I9xIN9VqOTlNc2Uc5Z0qJWA=,tag:8f/U0yIWxleRbsA/TxLgqQ==,type:str]
    jellyfin.client_secret.key: ENC[AES256_GCM,data:sfcO1eFfEUowWIPaRgMYazLZREstX4JOgzQsmLQryDxsQVDRplREQ8pS7bZ8j6CrwdIIwdM7zcZh7gZBvpECgW4J3b4KMG6z,iv:xKpQ/Pr4f7Psi7S3VOByOES5X0Yhqh2RkCHApSWy6ME=,tag:N4gD1khxML3z4b6mMDIwLQ==,type:str]
    vaultwarden.client_secret.key: ENC[AES256_GCM,data:8at8LssdlVh2eF6DCFBT9GYkxXL+pc8sSB/hlNXSFq6+tmiXUA8pyotveJZqFrJDpU90svGenXMh0egHMQEHCvHCm2j9iaw/,iv:Uvf4Sg2Cy48a9xu9NV13msxEqgpyHarNOq6FXy2yKiM=,tag:eQvdlapCNqPyvlN/kt+obA==,type:str]
    grafana.client_secret.key: ENC[AES256_GCM,data:39BCYRnYqwaaReGAM9QNH7P6UkuTjUob4NrGMVbNH/yTj2eyFcvGAbooWaXceYY2f8oLHjT8/CWWI4+UELKIeLIowQN5krYV,iv:GAntxz47/UrcMDkZYFJsh8hns0AlDfF4fLvvyLftzVc=,tag:nsJzGPqchV2jAWl2lAeKbA==,type:str]
    jellyseerr.client_secret.key: ENC[AES256_GCM,data:UGrxGqRlRE6vFlk8WKovYwRw2A8iUUVNdbI5zrytDw7u+tGNShcclFzO3chd2rwmIdpqS+LND3bpZ04wgZ7lKrVt8tohzb9G,iv:kQb8E2U2vCoUMJqdS7eQ3jJxM1bj6cqqqTZaVNg1ZpQ=,tag:1NiJDNI9LtP5Ai9XvC6iAA==,type:str]
    kavita.client_secret.key: ENC[AES256_GCM,data:Xsfp3Hwl/S8PVDImxkTZynGzbs4AWxZild6Qgrq3gig35gqhA4iDbpdn9Lo8aPrpvqxkleGvMkzRSeFdBA8B6GgJVqukKy6H,iv:WIEx51kA6f3k3MVNs8nXh5R+4uuJDFDAPArDYS1PAcI=,tag:sU4D1lE4ToMMwG1xyicCwA==,type:str]
    open-webui.client_secret.key: ENC[AES256_GCM,data:UbTeYeLdgNa4GdcslHeFZX9Zp4FA+PJsLOJf8x0yJeo+7tNyrGPnEcUc4jZrL/Xz3RgBI++lTnejCruCF3r+CA==,iv:hrH/Mk6km20NzyaIq5gTCFohUnlva4fy344JV4m0IQU=,tag:5I2wtZ6AGPweWlKpnEem6g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3clN2cVlmZnIvV3B5ZjBR
            OVJsU3hNRWY0QkNNbGlKY3RKbjhrL0VUVUZVCi9lcDMxWXJzQW9kd0V1dEluMUpC
            TWZ2dElneHJud1F6NUtEQmp6SWR2TUEKLS0tIDFSZ0txblY1aXAzTlJvU3puRDJh
            d0xGZ0FPamFDWWhwU2VrM3RpdFFYdmMKU96DEQlK1Ay1oa4c7zEpqzrxKgsb1lHc
            dypr9F4TXU9Mn8sZt/NaZJuRh5U/GCDcuWGROWNYqeuiHjSFSw+ieg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1m38eu4srfs6puqtrpcazlu5kv24fd57yda4p505k9msqjwzttujs825kzl
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-09T17:39:59Z"
    mac: ENC[AES256_GCM,data:vAUD7uc5Dl0GcnrPAwj8rOVwfgA/YvUXoavMy0ZBNBT6cZD7NBwke8clPd3ZLBMQyfz2EgTViaFbPLD760dWbpD4qQWpcJbvvIrOd2bIBpxLKIi9xM8K/lAMg8GCmHfmldlTfDL0UdaPUFwMdYbcyyzXT5m+DhpG2RTC47Pir3E=,iv:jGjAXy+jvtYxQ8pgPcsW84v0euoI+kvfqyj0FfWQfag=,tag:NTHDqDrByE3HjBnIfb7UkA==,type:str]
    pgp:
        - created_at: "2026-08-09T17:33:07Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIOA4TLBMScuBokEAf/aeQ3+uIvmSsoIMPSte4QNr2Tm0fVesKthSw/Lyw5UZdS
            ddmHP66WYHzwIntmRxR0PVGp7oRVIPGMaZXgg+NjyUT9M0rZAQJjuswYhSKYkZcT
            uWw4y44HpTBub0OIjMF9RX5pgx8Nw2vXPAZ73PD472muOb1m09kxOnmmbpId+1SG
            FpvEDhGMZ2rGZlS6ViD832XnaaFipGpFuQUvWp869aEhzazGt1czuo9hTlXiYE0f
            faGk/2JaZkUApFB9YYHtUDZnAGXwkprLlUbbqPLUj9HkoPyw93txEqvaGcPu45aX
            3upbMVYIYzTRnPV/loXtwF9morrOQiUdp7LJj+W1PQf+MbOT48ZKNXWOU12nGPLo
            G9aSRJJ/KRmFsOW/nPeNVQGn134vCSuEYMNZ78m9mx7f9tMmMkikU4oP9pWrapsl
            XKHZdqoMy/v3g7WkVjH/4vg+vSKgu8ugxK64CNfg7ic+eUY+aDPf6pFoy+sSs7qE
            fQX3eJUP/+urnS25VwJdU4ycz/mtGdQgxDamzqt/lILDyUPG35h+aN58fnfPM0H4
            n0267ZgoCy1b4QzEPz+82aGT64MX2CHadTOiTtCSgPpnQg2KPITboVUBiVnhF27p
            72sdmsaodMkrgJMWFk6V7WkRQl2fvwXkYHgnrKlwledS2jzsurFsAYVpeBQSuNOJ
            EtJeAWOJog07ufGhyyMDOYtRFxf/RqJaDyDVLw7yuNy1uctPkKEt9ie86cDKbOmG
            TjRfnQv15ffYf3sO7MGFuMgb/RuFBMD7lW1HCvZYfc3KapdNeaFSwtMxOAmCJcl7
            yg==
            =pc04
            -----END PGP MESSAGE-----
          fp: C8DAE39DAA00FF97
    version: 3.13.2
