---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: authelia-cnpg-cluster
  namespace: auth
  # annotations:
  #   cnpg.io/hibernation: "on"
spec:
  instances: 1
  imageName: ghcr.io/cloudnative-pg/postgresql:17.6

  # FIXME: this is only necessary because the previous cluster was using
  # postgres as owner of Authelia tables. Should move to authelia role instead.
  enableSuperuserAccess: true

  storage:
    size: 1Gi
    storageClass: longhorn-nvme-3-replicas

  bootstrap:
    recovery:
      database: main
      owner: authelia
      volumeSnapshots:
        storage:
          name: authelia-cnpg-restore-source
          kind: VolumeSnapshot
          apiGroup: snapshot.storage.k8s.io

  managed:
    services:
      disabledDefaultServices: ["ro", "r"]
      additional:
        - selectorType: rw
          serviceTemplate:
            metadata:
              name: authelia-cnpg
            spec:
              type: LoadBalancer
              loadBalancerClass: tailscale
          updateStrategy: patch

  monitoring:
    enablePodMonitor: true
