---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: music-assistant
  namespace: argo-system
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://bjw-s-labs.github.io/helm-charts
    chart: app-template
    targetRevision: 5.0.1
    helm:
      releaseName: music-assistant
      valuesObject:
        controllers:
          main:
            type: deployment
            replicas: 1
            annotations:
              reloader.stakater.com/auto: "true"
            containers:
              main:
                image:
                  repository: ghcr.io/music-assistant/server
                  tag: "2.9.9@sha256:50666a6f8d7f87d53d993dc41860ab06dda11047f6e433bb5bdbcb6e309ac74c"
                env:
                  LOG_LEVEL: info
                probes:
                  liveness:
                    enabled: false
                  readiness:
                    enabled: false
                  startup:
                    enabled: false

        service:
          main:
            type: LoadBalancer
            controller: main
            ipFamilyPolicy: RequireDualStack
            ipFamilies:
              - IPv4
              - IPv6
            annotations:
              io.cilium/lb-ipam-ips: "10.0.3.4,fd00:cafe::3:4"
            ports:
              http:
                port: 8095
              streaming:
                port: 8097

        route:
          internal-gw:
            enabled: true
            kind: HTTPRoute
            hostnames: [mass.home.cianfr.one]
            parentRefs:
              - name: internal-gw
                namespace: networking
                sectionName: https
            rules:
              - matches:
                  - path: { type: PathPrefix, value: / }
                backendRefs:
                  - identifier: main
                    port: http

        persistence:
          tmp:
            enabled: true
            type: emptyDir
            globalMounts:
              - path: /tmp
          data:
            enabled: true
            type: persistentVolumeClaim
            existingClaim: music-assistant-data-v2
            globalMounts:
              - path: /data
  destination:
    name: in-cluster
    namespace: home-automation
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - ServerSideApply=true
      - ApplyOutOfSyncOnly=true
      - SkipDryRunOnMissingResource=true
