---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argo-system
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://charts.jetstack.io
      chart: cert-manager
      targetRevision: v1.20.2
      helm:
        releaseName: cert-manager
        valueFiles:
          - $values/kube/home/networking/cert-manager/values.yaml
    - repoURL: git@github.com:iitsdani/homelabs.git
      targetRevision: refs/heads/main
      ref: values
  destination:
    name: in-cluster
    namespace: networking
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - ServerSideApply=true
      - ApplyOutOfSyncOnly=true
      - SkipDryRunOnMissingResource=true
