apiVersion: v1
kind: Secret
metadata:
    name: renovate-credentials
    namespace: default
type: Opaque
stringData:
    RENOVATE_TOKEN: ENC[AES256_GCM,data:j5qavGUjyJJSz6iM2c1PR070HO1rAfQMt6wt6v++RVyjcERqzMsLcLB3JkmGo3TnmWTGKF2thzfXPgVWRYKtulTJhxc86r4VWjTwlZoU5h4mT022XhSJkpyjhi6S,iv:4sKmU90tBuJSlRYQaQ7zfWuK4+FjOC4/fSP4EjvHi88=,tag:h1qcv2Vdo70wHL/jSN06iQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOYi9ReE9QNWh4V1pHaDZE
            Zno2UitUeWtsZTlqcTRHTUdGc011TTlUTkRvCllCZUIyZTNmcmNsUDkrY1BLR1J6
            ZkhkS0FnUVMwS1ZsNTdKTWxwQWhVWFUKLS0tIGRSOERoblZPb3FKcDhMaFlHZm5Z
            UHgrRnhjVXpNekJybmU5b1lLc0dvRzgKwrdTKg7U+CZO+JcINdeUSa/thfRHIIyG
            D3Fl4Gz7m2YfmGZvdmepvYNQX4wxbXy0YOjAsqcfSNYcOQWtZehOJg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1m38eu4srfs6puqtrpcazlu5kv24fd57yda4p505k9msqjwzttujs825kzl
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-20T15:30:00Z"
    mac: ENC[AES256_GCM,data:Bg3ysOSk2mo5MmEZhH7DZrHtYrgNGgdbPy2Ud/25fPrNRJxfSSZElsxtSyKRCtakebjhGDt0PTmMWixBDonqkcT7LwFdG92l7h+LV+vTqjh0H5CApDZq3A2gahVXjr4ZmutLquT0Pfh4oGq4Hfp93sITFbR1oStlmYUoO/HeXwo=,iv:GQe7mKHoKxBBy8+SkWoQij963t6I4q7jdHt2O6L568A=,tag:gZn4XjzoMDpymozOO/AHMg==,type:str]
    pgp:
        - created_at: "2026-07-20T15:29:15Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIOA4TLBMScuBokEAf/XFS/0J9mbEVbtsnGdD95THlwwHYGDtD7Stpyw/3dpw88
            xTfrDWwY/1std2MkbuqqKHtlMvNektNPouMqxLoNfQWEe05JzKKKwekcAalyr3Uu
            6jbX6SUSpyYTpdjewvwuWOmwdaucOyPtTvJTgoIq4Z1wtxbgeCwaVOA341fT9+wi
            kz6U9+HK1UZes3wIBJK7bPg1vZm0BuQXGi5HT4BPIxQAyMge0M4DXLmiAsuI8VHu
            UhESkalzJ1YDiAu7gh0l6Sz1W18A8cI3Wd3FZK9Ev8ytImKx5nyqEbkdrPszvzfj
            BeZldDwH5ATg1LzWPISpbx4cdnxzLIXghT4YYCV5GwgAjwq3C0z/KYb+DJ5qT0Md
            9D8qO4ouN/ejJjFVXOm7qVkQFWAaAtFZjYCXWeeKikUcHnJGpOaArjocdUBACY2o
            aMbI6rkW5w87u+QxDpgZxceTHo639uAXVyJ7SwbmTsbZ3/b9j6OCNtI065hfdEqB
            zYWUYDre18aMlMjVWdRlbyRwzfKG1SjXMZV2J9HoBh+nUtpJGS5dvcDC8OLWF43j
            8qYzPFdy2GD88INR9napw62LjYXMqmKM94anSpl+ied0bNxYX+Zk0sg5C71956YO
            BuGjFIQqgapC7eHlGphg2RFzuaRB8+EXc9H7MzOYHlZCq2JtNqNb2W/We4X4AAoX
            1NJeAfahJO8QpqvSte5SvL6VVshzwoL19D3ap/oz7agTj+D988i4ph3HkFaB3tHv
            b8N/x3Ksv2+ADxNoJ9CK/2yFbzWOPvnSzwZ7xO0MB2KfTWJijbeSULvMVFWWpoIe
            Uw==
            =+S3R
            -----END PGP MESSAGE-----
          fp: C8DAE39DAA00FF97
    version: 3.13.1
