---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mosquitto
  namespace: argo-system
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://bjw-s-labs.github.io/helm-charts
    chart: app-template
    targetRevision: 5.0.1
    helm:
      releaseName: mosquitto
      valuesObject:
        defaultPodOptions:
          securityContext:
            runAsNonRoot: true
            runAsUser: 1883
            runAsGroup: 1883
            fsGroup: 1883
            fsGroupChangePolicy: OnRootMismatch
            seccompProfile:
              type: RuntimeDefault

        controllers:
          main:
            type: deployment
            replicas: 0
            strategy: Recreate
            annotations:
              reloader.stakater.com/auto: "true"
            containers:
              main:
                image:
                  repository: docker.io/library/eclipse-mosquitto
                  tag: 2.1.2-alpine@sha256:a908c65cc8e67ec9d292ef27c2c0360dbaaee7eb1b935cdd194e67697f15dea1
                probes:
                  liveness: &probe
                    enabled: true
                    custom: true
                    spec:
                      tcpSocket:
                        port: 1883
                      initialDelaySeconds: 5
                      periodSeconds: 10
                  readiness: *probe
                securityContext:
                  runAsNonRoot: true
                  runAsUser: 1883
                  runAsGroup: 1883
                  seccompProfile:
                    type: RuntimeDefault
                  allowPrivilegeEscalation: false
                  capabilities:
                    drop:
                      - ALL
                  readOnlyRootFilesystem: true

        service:
          main:
            controller: main
            type: ClusterIP
            ports:
              mqtt:
                port: 1883
              ws:
                port: 1882

        persistence:
          config:
            enabled: true
            type: configMap
            name: mosquitto-config
            globalMounts:
              - path: /mosquitto/config/mosquitto.conf
                subPath: mosquitto.conf
                readOnly: true
          data:
            enabled: true
            type: persistentVolumeClaim
            existingClaim: mosquitto-data
            globalMounts:
              - path: /mosquitto/data
          log:
            enabled: true
            type: emptyDir
            globalMounts:
              - path: /mosquitto/log
  destination:
    name: in-cluster
    namespace: home-automation
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - ServerSideApply=true
      - ApplyOutOfSyncOnly=true
      - SkipDryRunOnMissingResource=true
