---
apiVersion: tailscale.com/v1alpha1
kind: Connector
metadata:
  name: internal-gw-subnet-router
spec:
  hostname: internal-gw-subnet-router
  subnetRouter:
    advertiseRoutes:
      - 10.0.3.11/32
      - fd00:cafe::3:11/128
  tags:
    - tag:k8s