---
# yaml-language-server: $schema=https://www.schemastore.org/kustomization.json
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - envoy-gateway-crds-application.yaml
  - envoy-gateway-controller-application.yaml
  - gatewayclass.yaml
  - external-gw-envoyproxy.yaml
  - external-gw-certificate.yaml
  - external-gw-gateway.yaml
  - external-gw-gateway-http-redirect.yaml
  - internal-gw-envoyproxy.yaml
  - internal-gw-certificate.yaml
  - internal-gw-gateway.yaml
  - internal-gw-gateway-http-redirect.yaml
  - controller-metrics.yaml
  - proxy-metrics.yaml
