---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyProxy
metadata:
  name: tailscale-gw
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  ipFamily: DualStack
  shutdown:
    minDrainDuration: 10s
    drainTimeout: 60s
  provider:
    type: Kubernetes
    kubernetes:
      envoyDeployment:
        replicas: 2
        container:
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
        pod:
          topologySpreadConstraints:
            - maxSkew: 1
              topologyKey: kubernetes.io/hostname
              whenUnsatisfiable: DoNotSchedule
              labelSelector:
                matchLabels:
                  gateway.envoyproxy.io/owning-gateway-name: tailscale-gw
      envoyService:
        externalTrafficPolicy: Local
        loadBalancerClass: tailscale
      envoyPDB:
        minAvailable: 1

