---
# IPv4 peer to RouterOS gateway. iBGP within AS 64512.
apiVersion: cilium.io/v2
kind: CiliumBGPPeerConfig
metadata:
  name: router-v4
  annotations:
spec:
  families:
    - afi: ipv4
      safi: unicast
      advertisements:
        matchLabels:
          advertise: bgp
  timers:
    holdTimeSeconds: 90
    keepAliveTimeSeconds: 30
    connectRetryTimeSeconds: 12
  gracefulRestart:
    enabled: true
    restartTimeSeconds: 120
