---
# yaml-language-server: $schema=https://www.schemastore.org/kustomization.json
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - application.yaml
  - persistentvolumeclaims.yaml

generators:
  - ksops.yaml

configMapGenerator:
  - name: home-assistant-configuration
    namespace: home-automation
    files:
      - ./config/configuration.yaml
      - ./config/scenes.yaml
      - ./config/scripts.yaml
  - name: home-assistant-automations
    namespace: home-automation
    files:
      - ./automations/home.yaml
      - ./automations/kitchen.yaml
      - ./automations/litter-robot.yaml
      - ./automations/toilet.yaml
      - ./automations/vacuum.yaml

generatorOptions:
  disableNameSuffixHash: true
