---
# yaml-language-server: $schema=https://www.schemastore.org/kustomization.json
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - application.yaml
  - persistentvolumeclaims.yaml
  - route.yaml
  - v2-application.yaml
  - v2-persistentvolumeclaim.yaml
  - vaultwarden-cnpg-cluster.yaml

generators:
  - ksops.yaml
