apiVersion: v1
kind: Secret
metadata:
    name: vaultwarden-secrets
    namespace: auth
type: Opaque
stringData:
    smtp-user: ENC[AES256_GCM,data:1+0LCLCIdrmJnQcv+2szaxsq3ihkcoELfFEZAA==,iv:TYnIM3VVpcSmTESM0GC6fGeC4VCy2cE3nSBzhSQaE68=,tag:0Ob3M6i+TD04+MlyAlxp9Q==,type:str]
    smtp-password: ENC[AES256_GCM,data:73+qi6sgIrjIofJcVRworRSVBw==,iv:EHnTVLHhe/lmcwHUI2Ow5gC8QsMrAilVyLfGkVIJCZQ=,tag:CXP5qwQxsVlAFOvXjyyenQ==,type:str]
    admin-token: ENC[AES256_GCM,data:PBqA1Qm79OWwdvqup0dW8Z2o2v3qLJBiSyLIUjzpGmbqDXMVj4tDNH4IbDeL3CGugY0qKYI835J7bWmDoCDpjrxAqSuTv1EIZIJ951nhRbFbVZjCQ3Z3THCLp0lHuKysNgEENBSFGqBn3PrhH2hUFGUGfxo98Q==,iv:niE25LwEUwYF3W9YUYlqoaudqS+jQfXdtmpnGN6G/cg=,tag:utdPRt4hcgtLkY07xYeL2g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArekdDSUhtVVpHc0ZNMXFX
            UEhqbVJTSDhKNUJhVjdIWU1pa1U2MWlpYWhJCml4cDZmWTRKU3dmTlhiWUdPdmVD
            RTZLcmdaSVd1YUFscEFYQzVDekFLZzgKLS0tIG1yUFpqQjdRbG90Q2k1YW9tNXVF
            aFRjakdUTzBBVmc4WFZZTGk5TGJ1QjgKAIdZE21qmNuaggrJHfWhcZis4hwpDyAr
            rt3sij+QHhaYfXYqKJGGBdh42V5kjUZ3dfPzfDOtGG6ufcjJKMW5YQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1m38eu4srfs6puqtrpcazlu5kv24fd57yda4p505k9msqjwzttujs825kzl
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-23T16:03:17Z"
    mac: ENC[AES256_GCM,data:696o8kNpKjf5vHGluVHSfhrTESRaSWI+SP1G6Vo2KzhwNiC0gdgMzjy4vTo9o+EO5NgHuZo+83NAc7uKnbbMW9GjuZv6Cv/v3fEMhNB+Zc44q4nD+VQI/Vein8X6KJ70Qkd2Q1YulyiEj477nVrpAymQkZDkH9vOWC+JkWmOmD8=,iv:CUuhT+Yu4OZizvV0d0h0xF+fgMRiD9L7EvEIX+EhDt4=,tag:uIBuIEnGfg2l8/dWJa7YkA==,type:str]
    pgp:
        - created_at: "2025-11-23T22:40:47Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIOA4TLBMScuBokEAf/Sa/N0kWUkeX4jjonNrgltqeUISlRklHkLd9VGhxB8ULe
            3P+HsWwiaK/vF/27SPzejD62dOA6az79//m9MdYvbfjuw2PaQv+dfZGykzJFMFqH
            wy1CJmiCbDmDtJpm/ffWenZdN+v4eS9DK40z02uRr9uX+Ecwv5TSY9KoTwjHzWZi
            AJnlFaHgyCyWrduE2ehczAdU7LV3ulK0f5rmQS6e1UEMTOsZeXgmmoaxCsesU6+s
            jlKOcjHahvuDYJHZaGsV23EFBBqoKf1wAamJM9L+RhAjcB1lLova/O2T38pdbt6z
            jwHdX1scQsD6bm3+/quRyLkfNad8f39j2/1PNv42xAf+LDXZkbql0AjAIU0p/YpW
            hDlFKHkQiF1EdvlIEjVeWklT/7PDMtfP3FHRj40tZqTgVHvv3cGJqmQfGcUFmyEO
            gJhSstqcS7Ge+4JKunG28S6D1DjJF+D1f7PaeNcJq/woexhl6ZDFTWCaF/stv27P
            pRNBInScOZ3PyJ+mLO5JfqJMcqrJgqv783RMFBDGW+xSIOdzJFZFdCDP3R5s3mi/
            ODwXFRgSuzH9e9J9tCfLE5RF0nqoc7Ujoj5jA3poB3VP+1p3i3UupZDI0nigbrgD
            ZMDHhfE1uhqlmBRgp7bfxFl8imjl8fSnWm92EB0kVTI8UnnghzkYJad6nkv8AMy+
            /9JeATZUCK0Gc5vNPP1uvLoCtigNGMtzCN8kATq59kq+jovRZlvGLwqoi6xzEjCX
            o1f7Fu/QV2bzLyyOvkJRu4AkRZ3F9Im7zqsjBK74kncic7eV7D6OxHxcg1Yx8zcH
            3w==
            =VUzt
            -----END PGP MESSAGE-----
          fp: C8DAE39DAA00FF97
    version: 3.11.0
