---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn
  namespace: argo-system
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://charts.longhorn.io
    chart: longhorn
    targetRevision: 1.11.3
    helm:
      releaseName: longhorn
      valuesObject:
        preUpgradeChecker:
          jobEnabled: false
        longhornUI:
          replicas: 2
        metrics:
          serviceMonitor:
            enabled: true
        ingress:
          enabled: false
        defaultSettings:
          v1DataEngine: false
          v2DataEngine: true
          defaultDataLocality: best-effort
          storageMinimalAvailablePercentage: "10"
          allowVolumeCreationWithDegradedAvailability: false
          allowCollectingLonghornUsageMetrics: false
          autoCleanupSnapshotWhenDeleteBackup: true
          autoCleanupSnapshotAfterOnDemandBackupCompleted: true
          snapshotDataIntegrityImmediateCheckAfterSnapshotCreation: true
          detachManuallyAttachedVolumesWhenCordoned: true
          rwxVolumeFastFailover: true
          nodeDownPodDeletionPolicy: delete-both-statefulset-and-deployment-pod
          replicaSoftAntiAffinity: false
          replicaAutoBalance: least-effort
          lockedVolumeAutoCleanup: true
          freezeFilesystemForSnapshot: true
          concurrentAutomaticEngineUpgradePerNodeLimit: 3
          replicaReplenishmentWaitInterval: 60
        defaultBackupStore:
          backupTarget: nfs://truenas.home.arpa:/mnt/zpool-nl-01/longhorn-backups-v2?nfsOptions=soft,timeo=330,retrans=3
          pollInterval: 300
  destination:
    name: in-cluster
    namespace: longhorn-system
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - ServerSideApply=true
      - ApplyOutOfSyncOnly=true
      - SkipDryRunOnMissingResource=true
