---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-home
  namespace: flux-system
spec:
  interval: 1m
  retryInterval: 1m
  timeout: 10m
  path: ./kube/home
  prune: true
  deletionPolicy: WaitForTermination
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  decryption:
    provider: sops
    secretRef:
      name: flux-sops-age-key
  patches:
    # 1. Defaults for child Flux Kustomization CRs.
    - target:
        group: kustomize.toolkit.fluxcd.io
        version: v1
        kind: Kustomization
      patch: |-
        apiVersion: kustomize.toolkit.fluxcd.io/v1
        kind: Kustomization
        metadata:
          name: not-used
        spec:
          interval: 1m
          retryInterval: 1m
          timeout: 10m
          prune: true
          deletionPolicy: WaitForTermination
          sourceRef:
            kind: GitRepository
            name: flux-system
            namespace: flux-system
          decryption:
            provider: sops
            secretRef:
              name: flux-sops-age-key
    # 2. Defaults for HelmRelease resources applied by root or child builds.
    - target:
        group: helm.toolkit.fluxcd.io
        version: v2
        kind: HelmRelease
      patch: |-
        apiVersion: helm.toolkit.fluxcd.io/v2
        kind: HelmRelease
        metadata:
          name: not-used
        spec:
          interval: 10m
          install:
            crds: CreateReplace
            remediation:
              retries: 3
          upgrade:
            crds: CreateReplace
            remediation:
              retries: 3
          driftDetection:
            mode: enabled
