---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-dns-cloudflare
  namespace: argo-system
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://kubernetes-sigs.github.io/external-dns/
    chart: external-dns
    targetRevision: 1.21.1
    helm:
      releaseName: external-dns-cloudflare
      valuesObject:
        provider: cloudflare
        managedRecordTypes:
          - A
          - AAAA
          - CNAME
        policy: sync
        domainFilters:
          - cianfr.one
        sources:
          - ingress
          - gateway-httproute
        env:
          - name: CF_API_TOKEN
            valueFrom:
              secretKeyRef:
                name: external-dns-secrets
                key: CLOUDFLARE_API_TOKEN
        serviceMonitor:
          enabled: true
  destination:
    name: in-cluster
    namespace: networking
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - ServerSideApply=true
      - ApplyOutOfSyncOnly=true
      - SkipDryRunOnMissingResource=true
