# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/refs/heads/master/v1.34.2/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secrets
    namespace: networking
type: Opaque
stringData:
    CLOUDFLARE_API_TOKEN: ENC[AES256_GCM,data:oOunh97B4SAvaGnS8KDC05M0U8ut40FUv6Ie7ocxn9NPeCPyMd+xdw==,iv:k11DdoMYhq67oK5hKegh1fhhqSe+NVrZUGSVgOBS7Sw=,tag:2TczWIXd4sZEKVX1QKRDvQ==,type:str]
sops:
    age:
        - recipient: age1m38eu4srfs6puqtrpcazlu5kv24fd57yda4p505k9msqjwzttujs825kzl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuOHZ5RXZXaG1hTlFmRFh5
            OUtjZzVjU2RWS2ZHY0hQeG5JU2VCVi9Rb204Cmx3Y2drNnQzcnVYQ0hJOUR5djBD
            Y0I4ZCtVNVN5L1lYVk9iUytuL2hpekUKLS0tIFA2RzlGTW95UmVsdERsaGVCT2FW
            dkFwZnBid2ZUUkdJM1pBb0k4T3Y4NjQKHIqQOHZxBzpcdk5RbIp4EEhGkzdcGfMN
            ZF/mLHxBmQmLuUzJzztVhW9pU6Av/ceQBg5Q8VIx71oahI80MyKkMg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-09T08:11:51Z"
    mac: ENC[AES256_GCM,data:kYYV3xSm8Ws8c0xcyPBi52ubgJgfKxiMeK8AY9rQiurqW2JidsV4+LZwyue+eb8/l+YyuIMX7hql7+XwwRw/bOv7nGy4gZaxerezc0NsHLYB1EQSaulYiCZLRM7EwcJNZJ9e4GrJX9EXP9udBHNTPQM+vYJKH6Se6QwHDM8cw8k=,iv:5HWiQuV9hlQI/SgHBqRm+HTo31AvIthjw1grMXJ4Jus=,tag:eGmfQphDOrhrXdY1rIVAzA==,type:str]
    pgp:
        - created_at: "2026-05-09T08:11:51Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIOA4TLBMScuBokEAgAkH/20Ny0joRXFY9WODFK/XdaSlD9Kn/zr0GIQgknWe0L
            zAb488Ne8uCaSlDooRCWFeEzjsrKA1IlPzjsB12ES85GXiQ+9mFeqtuErCHl1y3n
            ieo2wFEzX8/Mz8Rya21/Ij3e8u7lZHopqAxFKHfU6N4f1R1OT7qn7DIlgs7pK2Y9
            01dfWltSikmHK0wvlg5bHbCCHrGb8F2iOBGbRZyjjnwwgrZCHNhEuvrNofmBnTDR
            387OAocZOIBocMPSfQ8wz6WWThzjG2AsLrkxfmJfNX8vN58+it1G90/m1KD33fBB
            yzbXJnomQIDJiKAWnwUMkecJcN7HqwNdwkLg25sGDwf/UoagHTX1eewC6OLSjQXf
            FKtO5/cM8H+GY1hltvx54sxe54pqFAWDzGZaK1O9CcX/hKNIJ5Z4rlfYHK7WfiSX
            S0SDq08xCE3AzpeETkoz+R6orrw05fY+jsMoZIBZjTZ9t1CGDjbqqk2rU8eHlR+O
            kNGLAkYI7BSbZRtLJE25st678JjgEEptfqzcGwLSAZzqI5qoUI7kkxgZLnBnaiyc
            CyLYSIfglPII1pqx+vbsVvEPDp8eddK10baW0bIPUXZcwA+TdQ0PTTDAWVYITh2C
            rfy4AuknbWVtXy6F49l7ETLI/SQUVI/cGJpMITjO6xvif1JZmQc6kpri5+GQzlgh
            dNJRARoz7vzDS63szT86LDeR5P6PFaGbvfoM+kV/Qg9vYZAniiaDYgZ6pvCjWCHf
            6ZLqA37rR4eyjj3ZqqSVaS5rDQQqlwSPf/mBi3KVP2l0AROm
            =W78T
            -----END PGP MESSAGE-----
          fp: C8DAE39DAA00FF97
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
