---
apiVersion: viaduct.ai/v1
kind: ksops
metadata:
  name: external-dns-secrets-generator
  namespace: networking
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: ksops
files:
  - ./external-dns-secrets.enc.yaml
