---
provider: cloudflare

managedRecordTypes:
  - A
  - AAAA
  - CNAME
domainFilters:
  - cianfr.one
sources:
  - ingress
  - gateway-httproute

env:
  - name: CF_API_TOKEN
    valueFrom:
      secretKeyRef:
        name: external-dns-secrets
        key: CLOUDFLARE_API_TOKEN

serviceMonitor:
  enabled: true
