# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/values.schema.json
---
defaultPodOptions:
  securityContext:
    fsGroup: 1000
    fsGroupChangePolicy: OnRootMismatch
    runAsGroup: 1000
    runAsUser: 1000

service:
  main:
    type: ClusterIP
    controller: main
    ports:
      http:
        port: 6767

ingress:
  tailscale:
    className: tailscale
    enabled: true
    hosts:
      - host: nl-bazarr
        paths:
          - path: "/"
            pathType: Prefix
            service:
              identifier: main
              port: http
    tls:
      - hosts: [nl-bazarr]

controllers:
  main:
    type: deployment
    replicas: 1
    annotations:
      reloader.stakater.com/auto: "true"
    containers:
      main:
        env:
          PGID: 1000
          PGUID: 1000
          TZ: Europe/Amsterdam
        image:
          repository: ghcr.io/linuxserver/bazarr
          tag: 1.5.6@sha256:95f27692c3de6dbe130cd035d342d8138ec74ade7b62cfc52e11ae222c52c855
        probes:
          liveness: { enabled: false }
          readiness: { enabled: false }
          startup: { enabled: true }

persistence:
  config:
    enabled: true
    existingClaim: bazarr-config
    globalMounts: [{ path: /config }]
    type: persistentVolumeClaim
  media:
    enabled: true
    existingClaim: media-data-v4
    globalMounts: [{ path: /data }]
    type: persistentVolumeClaim
